import {selectRecallUnits} from './active-recall-model.mjs';
export function createActiveRecall({db,state,e,layout,toast,startSession,practice,legacy}) {
 let generation=0,cache=null,starting=false;
 const rpc=async(name,args)=>{const r=await db.rpc(name,args);if(r.error)throw r.error;return r.data;};
 const current=(user,g)=>state.user?.id===user&&generation===g;
 async function queue(limit=30,offset=0,due=true){return rpc('qbank_active_recall_queue',{p_limit:limit,p_offset:offset,p_due_only:due});}
 function summary(data){return `<b>${data.concepts_due} concepts due</b><p>+ ${data.questions_due} question-level items</p><small>${data.weak} Weak · ${data.learning} Learning · ${data.stable} Stable · ${data.mastered} Mastered</small>${data.personal_cards_due?`<p class="subtle">${data.personal_cards_due} personal recall card${data.personal_cards_due===1?'':'s'} also due (separate from MCQ recall).</p>`:''}`;}
 const sizes=()=>'<label>Session size <select id="ar-size"><option value="20">20</option><option value="30">30</option><option value="all">All Due</option></select></label>';
 async function mountHome(){const user=state.user?.id,g=++generation,host=document.querySelector('#active-recall-home');if(!host)return;try{const data=await queue(1);if(!current(user,g)||!host.isConnected)return;cache=data;host.innerHTML=`<span class="eyebrow">ACTIVE RECALL</span>${summary(data)}<div class="row">${sizes()}<button class="button" data-action="ar-start" ${data.due_count?'':'disabled'}>Start Active Recall</button></div><p><a href="#/recall">Concepts</a> · <button class="button ghost compact" data-action="ar-history">History</button></p>`;}catch(err){if(current(user,g)&&host.isConnected)host.innerHTML='<b>Active Recall unavailable</b><p>Please retry shortly. Your schedules are preserved.</p>';}}
 async function render(page=0){const user=state.user?.id,g=++generation;layout('<div class="page-heading"><span class="eyebrow">ACTIVE RECALL</span><h1>Previously encountered knowledge</h1></div><section class="card section-card" id="ar-content" role="status">Loading knowledge units…</section>');const host=document.querySelector('#ar-content');try{const data=await queue(30,page*30,false);if(!current(user,g)||!host.isConnected)return;cache=data;host.innerHTML=`${summary(data)}<div class="row">${sizes()}<button class="button" data-action="ar-start" ${data.due_count?'':'disabled'}>Start Active Recall</button><button class="button secondary" data-action="ar-history">History</button></div><details><summary>Advanced settings</summary><button class="button ghost" data-action="ar-legacy">Question-level queue and daily limits</button></details><p class="subtle">Finalized concepts are grouped. Unmapped questions remain separate; no text-similarity guesses are used.</p><ul class="list">${data.items.map(u=>`<li><div><b>${e(u.primary_concept||'Question-level recall')}</b><small>${e(u.subject)} · ${e(u.mastery)} · ${u.active?(u.due_at?new Date(u.due_at).toLocaleString():'Scheduled'):'Not enrolled'}</small></div><button class="button secondary" data-action="ar-details" data-id="${e(u.unit_key)}">Details</button></li>`).join('')}</ul><div class="row">${page?`<button class="button secondary" data-action="ar-page" data-page="${page-1}">Previous</button>`:''}${(page+1)*30<data.total?`<button class="button secondary" data-action="ar-page" data-page="${page+1}">Next</button>`:''}</div>`;}catch(err){if(current(user,g)&&host.isConnected)host.textContent=err.message;}}
 async function start(items=null){const user=state.user?.id,g=++generation;const size=document.querySelector('#ar-size')?.value||'20';let rows=items;
 if(!rows){const first=await queue(size==='all'?500:Number(size));rows=first.items;if(size==='all')for(let offset=500;offset<first.due_count;offset+=500){if(state.user?.id!==user)return;rows.push(...(await queue(500,offset)).items);}}
 if(!current(user,g))return;rows=selectRecallUnits(rows,'all');if(!rows.length)return toast('Nothing is due.');await startSession(rows,()=>current(user,g));
 }
 async function details(key){const user=state.user?.id,g=++generation;const data=await rpc('qbank_active_recall_detail',{p_unit_key:key});if(!current(user,g)||!data.unit)return;const unit=data.unit;cache={...cache,detail:unit};
 document.querySelector('#ar-dialog')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="ar-dialog"><section class="modal card" role="dialog" aria-modal="true" aria-label="Concept details"><div class="section-heading"><h2>${e(unit.primary_concept||'Question-level recall')}</h2><button class="button ghost" data-action="ar-close">Close</button></div><p>${e(unit.subject)} · ${e(unit.mastery)}${unit.tier?` · ${e(unit.tier)} importance (${unit.importance})`:''}</p><p>Last retrieval: ${unit.last_reviewed_at?new Date(unit.last_reviewed_at).toLocaleString():'Not recorded'}<br>Interval: ${unit.interval_minutes} minutes<br>Next due: ${unit.due_at?new Date(unit.due_at).toLocaleString():'Not scheduled'}</p><p>${unit.attempts||0} attempts · ${unit.correct||0} correct · ${unit.incorrect||0} incorrect<br>${data.confident_retrievals} confident V2 retrievals · ${unit.consecutive_failures} consecutive failures</p>${unit.primary_concept?`<p>NEET-PG ${unit.neet_pg_occurrences||0} · INI-CET ${unit.ini_cet_occurrences||0} · AIIMS ${unit.aiims_occurrences||0}</p>`:''}<details><summary>Encountered questions and platforms (${data.questions.length})</summary><ul>${data.questions.map(q=>`<li>${e(q.platform||'Unknown platform')} · ${e(q.question_id)}</li>`).join('')}</ul></details><details><summary>Mistake history (latest 30)</summary><ul>${data.mistakes.map(m=>`<li>${e(m.error_reason)} · ${new Date(m.answered_at).toLocaleString()}</li>`).join('')||'<li>No classified mistakes.</li>'}</ul></details><div class="row"><button class="button" data-action="ar-practice">Practice Concept</button><button class="button secondary" data-action="ar-previous-questions">View Previous Questions</button><button class="button secondary" data-action="ar-enroll" data-mode="${unit.active?'remove':'add'}">${unit.active?'Remove from':'Add to'} Recall</button></div></section></div>`);document.querySelector('#ar-dialog button')?.focus();
 }
 async function history(page=0){const user=state.user?.id,g=++generation;layout('<div class="page-heading"><h1>Active Recall history</h1><button class="button ghost" data-action="ar-page" data-page="0">Concepts</button></div><section class="card section-card" id="ar-history">Loading…</section>');const host=document.querySelector('#ar-history');const r=await db.from('qbank_srm_events').select('question_id,result,confidence,source,interval_minutes,occurred_at').eq('user_id',user).order('occurred_at',{ascending:false}).range(page*30,page*30+29);if(!current(user,g)||!host.isConnected)return;host.innerHTML=r.error?e(r.error.message):`<p class="subtle">Original question-level history is preserved, including events before V2.</p><ul class="list">${(r.data||[]).map(x=>`<li><div><b>${e(x.result)} · ${e(x.confidence||'No confidence recorded')}</b><small>${new Date(x.occurred_at).toLocaleString()} · ${e(x.source)} · ${x.interval_minutes} minutes</small></div></li>`).join('')}</ul>${page?`<button class="button secondary" data-action="ar-history" data-page="${page-1}">Previous</button>`:''}${r.data?.length===30?`<button class="button secondary" data-action="ar-history" data-page="${page+1}">Next</button>`:''}`;}
 async function handle(target){const action=target.dataset.action;if(!['ar-legacy','ar-start','ar-page','ar-details','ar-close','ar-history','ar-practice','ar-previous-questions','ar-enroll'].includes(action))return false;if(action==='ar-start'&&starting)return true;if(action==='ar-start')starting=true;target.disabled=true;try{
 if(action==='ar-legacy')await legacy();if(action==='ar-start')await start();if(action==='ar-page')await render(Number(target.dataset.page));if(action==='ar-history')await history(Number(target.dataset.page||0));if(action==='ar-details')await details(target.dataset.id);if(action==='ar-close')document.querySelector('#ar-dialog')?.remove();
 if(action==='ar-practice'){document.querySelector('#ar-dialog')?.remove();await start([cache.detail]);}
 if(action==='ar-previous-questions'){document.querySelector('#ar-dialog')?.remove();await practice(cache.detail.encountered_question_ids);}
 if(action==='ar-enroll'){await rpc('qbank_active_recall_manual',{p_question_id:cache.detail.question_id,p_action:target.dataset.mode,p_event_id:crypto.randomUUID()});await details(cache.detail.unit_key);}
 }catch(err){toast(err.message,'error');}finally{if(action==='ar-start')starting=false;target.disabled=false;}return true;}
 return {mountHome,render,handle,details,invalidate(){cache=null;},cancel(){generation++;document.querySelector('#ar-dialog')?.remove();}};
}
