import { db, initError, isMissingTable, requireUser } from './supabase.js';

const root = document.querySelector('#app');
const state = { user: null, route: 'home', meta: { subjects: [], platforms: [], systems: [], topics: [], tags: [] }, active: null, timer: null };
const e = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const date = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : '—';
const pct = (a, b) => b ? `${Math.round((a / b) * 100)}%` : '—';
const route = () => location.hash.replace(/^#\/?/, '').split('?')[0] || 'home';
const option = (items, selected, first = 'All') => `<option value="">${first}</option>${items.map((x) => `<option value="${e(x.id)}" ${String(x.id) === String(selected) ? 'selected' : ''}>${e(x.name)}</option>`).join('')}`;

function toast(text, kind = '') {
  const node = document.createElement('div'); node.className = `toast ${kind}`; node.textContent = text;
  document.querySelector('#toast-region').append(node); setTimeout(() => node.remove(), 3600);
}
function layout(content) {
  const nav = [['home', 'Home'], ['qbank', 'QBank'], ['tests', 'Tests'], ['history', 'History'], ['review', 'Review'], ['bookmarks', 'Bookmarks'], ['analytics', 'Analytics'], ['manage', 'Manage']];
  root.innerHTML = `<header class="topbar"><div class="shell"><a class="brand" href="#/home">QBank <span>Hub</span></a><div class="user-actions"><span class="email">${e(state.user.email)}</span><button class="button secondary" data-action="signout">Sign out</button></div></div><nav class="shell nav">${nav.map(([id, label]) => `<a href="#/${id}" class="${state.route === id ? 'active' : ''}">${label}</a>`).join('')}</nav></header><main class="shell">${content}</main>`;
}
function loading() { root.innerHTML = '<main class="shell"><div class="card empty">Loading QBank Hub…</div></main>'; }
async function maybe(query) { const result = await query; return result.error && !isMissingTable(result.error) ? (toast(result.error.message, 'error'), result) : result; }

async function loadMeta() {
  const [subjects, platforms, systems, topics, tags] = await Promise.all([
    db.from('subjects').select('id,name').order('name'), db.from('platforms').select('id,name').order('name'),
    db.from('systems').select('id,name').order('display_order').order('name'), db.from('topics').select('id,name').order('display_order').order('name'), db.from('tags').select('id,name').order('name'),
  ]);
  state.meta.subjects = subjects.data || []; state.meta.platforms = platforms.data || []; state.meta.systems = systems.data || []; state.meta.topics = topics.data || []; state.meta.tags = tags.data || [];
}
async function loadQuestions(filters = {}) {
  let query = db.from('questions').select('*');
  let answeredIds = null;
  if (filters.subject) query = query.eq('subject_id', filters.subject);
  if (filters.platform) query = query.eq('platform_id', filters.platform);
  if (filters.system) query = query.eq('system_id', filters.system);
  if (filters.difficulty) query = query.eq('difficulty', filters.difficulty);
  if (filters.pyq === 'yes') query = query.eq('is_pyq', true);
  if (filters.year) query = query.eq('exam_year', Number(filters.year));
  if (filters.source) query = query.ilike('source_reference', `%${filters.source.trim()}%`);
  if (filters.search) query = query.ilike('question_text', `%${filters.search.trim()}%`);
  if (filters.topic) { const { data, error } = await db.from('question_topics').select('question_id').eq('topic_id', filters.topic); if (error) throw error; query = query.in('id', (data || []).map((x) => x.question_id)); }
  if (filters.tag) { const { data, error } = await db.from('question_tags').select('question_id').eq('tag_id', filters.tag); if (error) throw error; query = query.in('id', (data || []).map((x) => x.question_id)); }
  if (filters.bookmarked === 'yes' || filters.marked === 'yes' || filters.incorrect === 'yes') {
    const source = filters.bookmarked === 'yes' ? db.from('bookmarks').select('question_id').eq('user_id', state.user.id) : filters.marked === 'yes' ? db.from('review_queue').select('question_id').eq('user_id', state.user.id).eq('reason', 'marked') : db.from('question_attempts').select('question_id').eq('user_id', state.user.id).eq('is_correct', false);
    const { data, error } = await source; if (error) throw error; query = query.in('id', [...new Set((data || []).map((x) => x.question_id))]);
  }
  if (filters.unanswered === 'yes') { const { data, error } = await db.from('question_attempts').select('question_id').eq('user_id', state.user.id); if (error) throw error; answeredIds = new Set((data || []).map((x) => x.question_id)); }
  const { data, error } = await query.limit(Math.min(Number(filters.count) || 10, 100));
  if (error) throw error;
  let rows = (data || []).filter((q) => !answeredIds || !answeredIds.has(q.id));
  if (filters.random !== false) rows = rows.sort(() => Math.random() - .5);
  return rows;
}
async function questionWithOptions(question) {
  const { data, error } = await db.from('question_options').select('question_id,option_key,option_text').eq('question_id', question.id).order('option_key');
  if (error) throw error;
  let imageUrl = question.image_url || '';
  if (!imageUrl && question.image_path) { const signed = await db.storage.from('question-media').createSignedUrl(question.image_path, 3600); imageUrl = signed.data?.signedUrl || ''; }
  return { ...question, image_url: imageUrl, options: data || [] };
}
async function loadSessionQuestions(rows) { return Promise.all(rows.map(questionWithOptions)); }

async function home() {
  loading();
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const [questions, attempts, sessions, bookmarks, review] = await Promise.all([
    db.from('questions').select('*', { count: 'exact', head: true }),
    db.from('question_attempts').select('id,is_correct,answered_at').eq('user_id', state.user.id).order('answered_at', { ascending: false }).limit(1000),
    maybe(db.from('test_sessions').select('*').eq('user_id', state.user.id).order('updated_at', { ascending: false }).limit(5)),
    maybe(db.from('bookmarks').select('*', { count: 'exact', head: true }).eq('user_id', state.user.id)),
    maybe(db.from('review_queue').select('*', { count: 'exact', head: true }).eq('user_id', state.user.id).lte('due_at', new Date().toISOString())),
  ]);
  const logs = attempts.data || []; const correct = logs.filter((x) => x.is_correct).length; const todayCount = logs.filter((x) => new Date(x.answered_at) >= today).length;
  const recent = sessions.data || [];
  layout(`<div class="row"><div><h1>Good to see you</h1><p class="subtle">A focused workspace for your next medical exam.</p></div><div class="row"><a class="button secondary" href="#/qbank">Continue practice</a><a class="button" href="#/tests">Start test</a></div></div>
  <section class="grid stats"><div class="card stat"><span class="label">Questions attempted</span><b>${logs.length}</b></div><div class="card stat"><span class="label">Questions available</span><b>${questions.count ?? 0}</b></div><div class="card stat"><span class="label">Accuracy</span><b>${pct(correct, logs.length)}</b></div><div class="card stat"><span class="label">Answered today</span><b>${todayCount}</b></div><div class="card stat"><span class="label">Due for review</span><b>${review.count ?? 0}</b></div></section>
  <section class="grid split" style="margin-top:16px"><div class="card"><div class="row"><h2>Recent tests</h2><a href="#/history" class="subtle">View history</a></div>${recent.length ? `<ul class="list">${recent.map((s) => `<li><div class="row"><div><b>${e(s.title || s.mode || 'Practice test')}</b><div class="session-row">${date(s.completed_at || s.created_at)} · ${s.question_count || '—'} questions · ${s.status}</div></div><span class="pill">${s.score == null ? 'In progress' : `${s.score}/${s.question_count}`}</span></div></li>`).join('')}</ul>` : '<div class="empty">Your completed and in-progress tests will appear here.</div>'}</div><div class="card"><h2>Study goal</h2><p class="subtle">Build a steady daily habit. Today you have answered <b>${todayCount}</b> questions.</p><div class="progress"><i style="width:${Math.min(todayCount * 10, 100)}%"></i></div><p class="subtle" style="margin:10px 0 0">Personal goal: 10 questions/day</p><p style="margin:16px 0 0"><span class="pill">${bookmarks.count ?? 0} bookmarked</span></p></div></section>`);
}

async function qbank() {
  await loadMeta();
  layout(`<div class="row"><div><h1>Build a practice set</h1><p class="subtle">Choose what to study, then start a focused set.</p></div></div><section class="card"><form id="practice-form" class="stack"><div class="filters"><div class="field"><label>Exam / platform</label><select name="platform">${option(state.meta.platforms, '')}</select></div><div class="field"><label>Subject</label><select name="subject">${option(state.meta.subjects, '')}</select></div><div class="field"><label>System</label><select name="system">${option(state.meta.systems, '')}</select></div><div class="field"><label>Topic</label><select name="topic">${option(state.meta.topics, '')}</select></div><div class="field"><label>Difficulty</label><select name="difficulty"><option value="">All difficulties</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div><div class="field"><label>PYQ</label><select name="pyq"><option value="">All questions</option><option value="yes">PYQ only</option></select></div><div class="field"><label>Exam year</label><input name="year" type="number" min="1950" max="2100" placeholder="e.g. 2024" /></div><div class="field"><label>Tag</label><select name="tag">${option(state.meta.tags, '')}</select></div><div class="field"><label>Personal status</label><select name="personal"><option value="">Any status</option><option value="bookmarked">Bookmarked</option><option value="marked">Marked for review</option><option value="incorrect">Previously incorrect</option><option value="unanswered">Unanswered</option></select></div><div class="field"><label>Questions</label><select name="count"><option>10</option><option>20</option><option>30</option><option>50</option><option>100</option></select></div><div class="field"><label>Experience</label><select name="timed"><option value="false">Untimed practice</option><option value="true">Timed practice</option></select></div><div class="field"><label>Explanation</label><select name="explain"><option value="after">After each answer</option><option value="end">At the end</option></select></div><div class="field wide"><label>Search question text</label><input class="input" name="search" placeholder="Search terms, e.g. thyroid, ECG, nephrotic" /></div><div class="field wide"><label>Source / reference</label><input class="input" name="source" placeholder="Source or platform reference" /></div></div><div><button class="button">Start practice</button></div></form></section>`);
  document.querySelector('#practice-form').onsubmit = async (event) => { event.preventDefault(); const f = Object.fromEntries(new FormData(event.currentTarget)); if (f.personal) f[f.personal] = 'yes'; await beginPractice(f); };
}

async function beginPractice(filters) {
  try { const questions = await loadSessionQuestions(await loadQuestions(filters)); if (!questions.length) return toast('No questions match those filters.'); state.active = { kind: 'practice', questions, index: 0, answers: {}, marked: {}, explain: filters.explain, startedAt: new Date().toISOString(), timed: filters.timed === 'true' }; renderActive(); } catch (error) { toast(error.message || 'Could not load questions.'); }
}

function activeQuestion() { return state.active.questions[state.active.index]; }
function timerText(ms) { const minutes = Math.max(0, Math.floor(ms / 60000)); const seconds = Math.max(0, Math.floor((ms % 60000) / 1000)); return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`; }
function showQuestion(q, answer, reveal) {
  const correct = (q.correct_answer || '').trim().charAt(0).toUpperCase();
  return `<div class="question-stem">${e(q.question_text)}</div>${q.image_url ? `<img class="question-image" src="${e(q.image_url)}" alt="Question illustration" />` : ''}<div>${q.options.map((o) => { const key = String(o.option_key).toUpperCase(); const classes = ['option']; if (answer === key) classes.push('selected'); if (reveal && key === correct) classes.push('correct'); if (reveal && answer === key && key !== correct) classes.push('wrong'); return `<button class="${classes.join(' ')}" data-action="answer" data-key="${e(key)}"><b>${e(o.option_key)}.</b> ${e(o.option_text)}</button>`; }).join('')}</div>${reveal ? `<div class="notice ${answer === correct ? 'ok' : ''}" style="margin-top:14px"><b>${answer === correct ? 'Correct' : `Correct answer: ${e(correct || 'Not provided')}`}</b>${q.explanation_html ? `<p style="margin:8px 0 0">${e(q.explanation_html)}</p>` : ''}${q.source_reference ? `<p class="subtle" style="margin:8px 0 0">Source: ${e(q.source_reference)}</p>` : ''}</div>` : ''}`;
}
function renderActive() {
  const a = state.active, q = activeQuestion(); if (!q) return;
  const answer = a.answers[q.id]?.selected_option || ''; const reveal = a.kind === 'practice' && a.explain === 'after' && Boolean(answer);
  const elapsed = Date.now() - new Date(a.startedAt).getTime();
  layout(`<div class="row"><div><span class="pill">${a.kind === 'test' ? 'Test mode' : 'Practice mode'}</span><h1 style="margin:8px 0 0">${a.title || 'Question set'}</h1></div>${a.kind === 'test' ? `<div id="timer" class="timer"></div>` : a.timed ? `<div class="timer">${timerText(elapsed)}</div>` : ''}</div><div class="question-layout" style="margin-top:16px"><section class="card"><div class="row"><span class="subtle">Question ${a.index + 1} of ${a.questions.length}</span><span class="subtle">${q.subjects?.name || q.subject_name || 'General'} ${q.platforms?.name ? `· ${e(q.platforms.name)}` : ''}</span></div><div class="progress" style="margin:12px 0"><i style="width:${((a.index + 1) / a.questions.length) * 100}%"></i></div>${showQuestion(q, answer, reveal)}<div class="row" style="margin-top:18px"><div class="row"><button class="button ghost" data-action="bookmark">Bookmark</button><button class="button ghost" data-action="mark">${a.marked[q.id] ? 'Unmark review' : 'Mark for review'}</button><button class="button ghost" data-action="note">Note</button><button class="button ghost" data-action="report">Report</button></div><div class="row"><button class="button secondary" data-action="previous" ${a.index === 0 ? 'disabled' : ''}>Previous</button><button class="button" data-action="next">${a.index === a.questions.length - 1 ? (a.kind === 'test' ? 'Review & submit' : 'Finish') : 'Next'}</button></div></div></section><aside class="card"><div class="row"><h3>Question palette</h3><span class="subtle">${Object.keys(a.answers).length}/${a.questions.length}</span></div><div class="palette">${a.questions.map((item, i) => `<button data-action="jump" data-index="${i}" class="${i === a.index ? 'current' : ''} ${a.answers[item.id] ? 'answered' : ''} ${a.marked[item.id] ? 'marked' : ''}" aria-label="Question ${i + 1}">${i + 1}</button>`).join('')}</div>${a.kind === 'test' ? `<p class="subtle" style="margin-top:14px">${a.questions.length - Object.keys(a.answers).length} unanswered</p><button class="button danger" data-action="submit">Submit test</button>` : ''}</aside></div>`);
  if (a.kind === 'test') startTimer();
}
async function selectAnswer(key) {
  const a = state.active, q = activeQuestion(); if (!a || (a.kind === 'test' && a.status === 'completed')) return;
  a.answers[q.id] = { selected_option: key, answered_at: new Date().toISOString() };
  if (a.kind === 'practice') await recordPractice(q, key);
  else await saveTestAnswer(q.id, key);
  renderActive();
}
async function recordPractice(q, key) {
  const correct = (q.correct_answer || '').trim().charAt(0).toUpperCase() === key;
  const { error } = await db.from('question_attempts').insert({ user_id: state.user.id, question_id: q.id, selected_option: key, is_correct: correct, mode: 'qbank', answered_at: new Date().toISOString() });
  if (error) toast(`Answer saved locally, but cloud sync failed: ${error.message}`);
  if (!correct) await maybe(db.from('review_queue').upsert({ user_id: state.user.id, question_id: q.id, reason: 'incorrect', due_at: new Date().toISOString() }, { onConflict: 'user_id,question_id' }));
}
async function toggleBookmark() { const q = activeQuestion(); const { data } = await maybe(db.from('bookmarks').select('id').eq('user_id', state.user.id).eq('question_id', q.id).maybeSingle()); if (data?.id) { await maybe(db.from('bookmarks').delete().eq('id', data.id)); toast('Bookmark removed'); } else { await maybe(db.from('bookmarks').insert({ user_id: state.user.id, question_id: q.id })); toast('Bookmarked'); } }
async function toggleMark() { const a = state.active, q = activeQuestion(); a.marked[q.id] = !a.marked[q.id]; if (a.kind === 'test') await saveTestAnswer(q.id, a.answers[q.id]?.selected_option || null); else await maybe(db.from('review_queue').upsert({ user_id: state.user.id, question_id: q.id, reason: 'marked', due_at: new Date().toISOString() }, { onConflict: 'user_id,question_id' })); renderActive(); }
function modal(title, body, submitLabel = 'Save') { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" id="modal"><div class="modal card"><div class="row"><h2>${e(title)}</h2><button class="button ghost" data-action="close-modal">Close</button></div><form id="modal-form" class="stack">${body}<button class="button">${e(submitLabel)}</button></form></div></div>`); }
async function noteModal() { const q = activeQuestion(); const { data } = await maybe(db.from('question_notes').select('*').eq('user_id', state.user.id).eq('question_id', q.id).maybeSingle()); modal('Personal note', `<div class="field"><label>Your private note</label><textarea name="body" placeholder="Key takeaway, memory aid, or doubt…">${e(data?.body || '')}</textarea></div>`); document.querySelector('#modal-form').onsubmit = async (ev) => { ev.preventDefault(); const body = new FormData(ev.currentTarget).get('body').trim(); if (!body && data?.id) await maybe(db.from('question_notes').delete().eq('id', data.id)); else if (body) await maybe(db.from('question_notes').upsert({ user_id: state.user.id, question_id: q.id, body }, { onConflict: 'user_id,question_id' })); document.querySelector('#modal').remove(); toast('Note saved'); }; }
function reportModal() { const q = activeQuestion(); modal('Report question', `<div class="field"><label>What needs attention?</label><select name="reason"><option value="wrong_answer">Wrong answer</option><option value="wrong_explanation">Wrong explanation</option><option value="ambiguous">Ambiguous question</option><option value="poor_quality">Poor-quality question</option><option value="broken_image">Broken image</option><option value="other">Other</option></select></div><div class="field"><label>Details (optional)</label><textarea name="details"></textarea></div>`, 'Send report'); document.querySelector('#modal-form').onsubmit = async (ev) => { ev.preventDefault(); const f = Object.fromEntries(new FormData(ev.currentTarget)); const { error } = await maybe(db.from('question_reports').insert({ user_id: state.user.id, question_id: q.id, ...f })); if (!error) { document.querySelector('#modal').remove(); toast('Thank you — report saved.'); } }; }

async function tests() {
  await loadMeta();
  layout(`<div><h1>Test builder</h1><p class="subtle">Every test is saved to your account and can be resumed on either device.</p></div><section class="grid two"><div class="card"><h2>New test</h2><form id="test-form" class="stack"><div class="filters"><div class="field"><label>Preset</label><select name="title"><option>Mixed Test</option><option>Subject-wise Test</option><option>Topic Test</option><option>PYQ Test</option><option>Grand Test</option></select></div><div class="field"><label>Platform</label><select name="platform">${option(state.meta.platforms, '')}</select></div><div class="field"><label>Subject</label><select name="subject">${option(state.meta.subjects, '')}</select></div><div class="field"><label>System</label><select name="system">${option(state.meta.systems, '')}</select></div><div class="field"><label>Topic</label><select name="topic">${option(state.meta.topics, '')}</select></div><div class="field"><label>Difficulty</label><select name="difficulty"><option value="">All difficulties</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></div><div class="field"><label>PYQ</label><select name="pyq"><option value="">All questions</option><option value="yes">PYQ only</option></select></div><div class="field"><label>Questions</label><select name="count"><option>10</option><option>20</option><option selected>30</option><option>50</option><option>100</option></select></div><div class="field"><label>Duration (minutes)</label><input name="duration" type="number" min="1" max="360" value="36" /></div><div class="field"><label>Include repeats?</label><select name="repeats"><option value="false">No, prefer new questions</option><option value="true">Yes</option></select></div></div><button class="button">Start timed test</button></form></div><div class="card"><h2>Resume a test</h2><div id="resume-tests" class="empty">Loading unfinished tests…</div></div></section>`);
  document.querySelector('#test-form').onsubmit = async (event) => { event.preventDefault(); await beginTest(Object.fromEntries(new FormData(event.currentTarget))); };
  const { data, error } = await maybe(db.from('test_sessions').select('*').eq('user_id', state.user.id).eq('status', 'in_progress').order('updated_at', { ascending: false }));
  const holder = document.querySelector('#resume-tests'); if (error && isMissingTable(error)) holder.innerHTML = '<div class="notice">Apply the included Supabase migration to enable durable timed tests.</div>'; else holder.innerHTML = data?.length ? `<ul class="list">${data.map((s) => `<li><b>${e(s.title || 'Test')}</b><div class="session-row">${s.question_count} questions · ${s.duration_minutes} min</div><button class="button secondary" data-action="resume" data-id="${s.id}">Resume</button></li>`).join('')}</ul>` : '<div class="empty">No unfinished tests.</div>';
}
async function beginTest(form) {
  try { const rows = await loadQuestions({ ...form, random: true }); const questions = await loadSessionQuestions(rows); if (!questions.length) return toast('No questions match the selected test filters.'); const now = new Date().toISOString(); const payload = { user_id: state.user.id, title: form.title, mode: 'test', status: 'in_progress', question_count: questions.length, duration_minutes: Number(form.duration), started_at: now, current_position: 0, filters: form }; const { data: session, error } = await db.from('test_sessions').insert(payload).select().single(); if (error) { if (isMissingTable(error)) return toast('Timed tests need the included migration before they can be saved.'); throw error; } const snapshots = questions.map((q, position) => ({ session_id: session.id, question_id: q.id, position, question_snapshot: { question_text: q.question_text, correct_answer: q.correct_answer, explanation_html: q.explanation_html, source_reference: q.source_reference, image_url: q.image_url, options: q.options } })); const created = await db.from('test_session_questions').insert(snapshots); if (created.error) throw created.error; state.active = { ...session, kind: 'test', questions, index: 0, answers: {}, marked: {} }; renderActive(); } catch (error) { toast(error.message || 'Could not start test.'); } }
async function resumeTest(id) { try { const { data: session, error } = await db.from('test_sessions').select('*').eq('id', id).eq('user_id', state.user.id).single(); if (error) throw error; const { data: items, error: itemError } = await db.from('test_session_questions').select('*').eq('session_id', id).order('position'); if (itemError) throw itemError; const { data: answers } = await db.from('test_answers').select('*').eq('session_id', id); const questions = items.map((item) => ({ id: item.question_id, ...item.question_snapshot, options: item.question_snapshot.options || [] })); const answerMap = Object.fromEntries((answers || []).map((x) => [x.question_id, x])); state.active = { ...session, kind: session.status === 'in_progress' ? 'test' : 'practice', title: `${session.title || 'Test'} review`, explain: 'after', questions, index: session.current_position || 0, answers: answerMap, marked: Object.fromEntries((answers || []).filter((x) => x.marked_for_review).map((x) => [x.question_id, true])) }; renderActive(); } catch (error) { toast(error.message); } }
async function saveTestAnswer(questionId, key) { const a = state.active; const value = { session_id: a.id, question_id: questionId, selected_option: key, marked_for_review: Boolean(a.marked[questionId]), answered_at: new Date().toISOString() }; await maybe(db.from('test_answers').upsert(value, { onConflict: 'session_id,question_id' })); await maybe(db.from('test_sessions').update({ current_position: a.index, updated_at: new Date().toISOString() }).eq('id', a.id).eq('status', 'in_progress')); }
function startTimer() { clearInterval(state.timer); const tick = () => { const end = new Date(state.active.started_at).getTime() + state.active.duration_minutes * 60000; const remaining = end - Date.now(); const el = document.querySelector('#timer'); if (el) { el.textContent = timerText(remaining); el.classList.toggle('low', remaining < 5 * 60000); } if (remaining <= 0) { clearInterval(state.timer); submitTest(true); } }; tick(); state.timer = setInterval(tick, 1000); }
async function submitTest(timedOut = false) { const a = state.active; if (!a || a.kind !== 'test' || a.status === 'completed') return; if (!timedOut && !confirm(`Submit this test? ${a.questions.length - Object.keys(a.answers).length} questions are unanswered.`)) return; clearInterval(state.timer); const { data, error } = await db.rpc('submit_test_session', { p_session_id: a.id, p_timed_out: timedOut }); if (error) return toast(error.message); const attempts = a.questions.flatMap((q) => { const selected = a.answers[q.id]?.selected_option; if (!selected) return []; return [{ user_id: state.user.id, question_id: q.id, selected_option: selected, is_correct: selected.toUpperCase() === String(q.correct_answer || '').trim().charAt(0).toUpperCase(), mode: 'test', answered_at: new Date().toISOString() }]; }); if (attempts.length) await maybe(db.from('question_attempts').insert(attempts)); state.active = { ...a, ...data }; testResult(); }
function testResult() { const a = state.active; const answered = Object.keys(a.answers).length; layout(`<div class="card"><span class="pill">${a.timed_out ? 'Time expired' : 'Submitted'}</span><h1 style="margin-top:10px">${e(a.title || 'Test result')}</h1><div class="grid stats"><div class="stat"><span class="label">Score</span><b>${a.score}/${a.questions.length}</b></div><div class="stat"><span class="label">Accuracy</span><b>${pct(a.score, answered)}</b></div><div class="stat"><span class="label">Correct</span><b>${a.correct_count}</b></div><div class="stat"><span class="label">Incorrect</span><b>${a.incorrect_count}</b></div><div class="stat"><span class="label">Unanswered</span><b>${a.unanswered_count}</b></div></div><p class="subtle" style="margin-top:16px">Time used: ${timerText(a.time_used_seconds * 1000)}${a.timed_out ? ' · Submitted automatically when time ran out.' : ''}</p><button class="button" data-action="review-result">Review questions</button><a class="button secondary" href="#/history">Test history</a></div>`); }

async function history() { const { data, error } = await maybe(db.from('test_sessions').select('*').eq('user_id', state.user.id).neq('status', 'in_progress').order('completed_at', { ascending: false })); layout(`<div><h1>Test history</h1><p class="subtle">Completed tests are saved with their original question snapshots.</p></div><section class="card">${error && isMissingTable(error) ? '<div class="notice">Apply the included migration to start recording test history.</div>' : data?.length ? `<ul class="list">${data.map((s) => `<li><div class="row"><div><b>${e(s.title || 'Test')}</b><div class="session-row">${date(s.completed_at)} · ${s.question_count} questions · ${s.timed_out ? 'Timed out' : 'Completed'}</div></div><div><span class="pill">${s.score}/${s.question_count}</span> <button class="button secondary" data-action="resume" data-id="${s.id}">Open</button></div></div></li>`).join('')}</ul>` : '<div class="empty">No completed tests yet.</div>'}</section>`); }
async function simpleQuestionList(kind) { const table = kind === 'bookmarks' ? 'bookmarks' : 'review_queue'; const { data, error } = await maybe(db.from(table).select('*').eq('user_id', state.user.id).order('created_at', { ascending: false })); const ids = (data || []).map((x) => x.question_id); let questions = []; if (ids.length) { const r = await db.from('questions').select('*').in('id', ids); questions = r.data || []; } layout(`<div><h1>${kind === 'bookmarks' ? 'Bookmarks' : 'Review queue'}</h1><p class="subtle">${kind === 'bookmarks' ? 'Your saved questions, synced across devices.' : 'Incorrect and marked questions waiting for another pass.'}</p></div><section class="card">${error && isMissingTable(error) ? '<div class="notice">This feature becomes available after applying the included migration.</div>' : questions.length ? `<ul class="list">${questions.map((q) => `<li><b>${e(q.question_text)}</b><div class="row"><span class="subtle">${q.subject_name || 'Question'}</span><button class="button secondary" data-action="open-one" data-id="${q.id}">Open</button></div></li>`).join('')}</ul>` : '<div class="empty">Nothing here yet.</div>'}</section>`); }
async function analytics() { const { data: attempts, error } = await db.from('question_attempts').select('question_id,is_correct,answered_at').eq('user_id', state.user.id).order('answered_at', { ascending: false }).limit(1000); if (error) throw error; const logs = attempts || []; const ids = [...new Set(logs.map((x) => x.question_id))]; const { data: questionRows } = ids.length ? await db.from('questions').select('*').in('id', ids) : { data: [] }; const questions = new Map((questionRows || []).map((q) => [q.id, q])); const tally = (key) => { const result = new Map(); logs.forEach((a) => { const id = questions.get(a.question_id)?.[key]; const v = result.get(id) || [0, 0]; v[0] += a.is_correct ? 1 : 0; v[1]++; result.set(id, v); }); return result; }; const correct = logs.filter((x) => x.is_correct).length; const bySubject = tally('subject_id'); const bySystem = tally('system_id'); const subjectNames = new Map(state.meta.subjects.map((s) => [s.id, s.name])); const systemsResult = await maybe(db.from('systems').select('id,name')); const systemNames = new Map((systemsResult.data || []).map((s) => [s.id, s.name])); const bars = (data, names) => data.size ? [...data.entries()].filter(([id]) => id).sort((a, b) => a[1][0] / a[1][1] - b[1][0] / b[1][1]).slice(0, 6).map(([id, [c, n]]) => `<div class="chart-row"><span>${e(names.get(id) || 'Unclassified')}</span><div class="bar"><i style="width:${Math.round(c / n * 100)}%"></i></div><b>${pct(c, n)}</b></div>`).join('') : '<div class="empty">Answer questions to see meaningful trends.</div>'; layout(`<div><h1>Performance</h1><p class="subtle">Based on your real answered questions only. The lowest-accuracy categories appear first.</p></div><section class="grid three"><div class="card"><h2>Overall</h2><div class="stat"><span class="label">Attempted</span><b>${logs.length}</b></div><div class="stat"><span class="label">Accuracy</span><b>${pct(correct, logs.length)}</b></div></div><div class="card"><h2>Weak subjects</h2>${bars(bySubject, subjectNames)}</div><div class="card"><h2>Weak systems</h2>${bars(bySystem, systemNames)}</div></section>`); }
function manage() { layout(`<div><h1>Question management</h1><p class="subtle">A deliberately small editorial foundation for your personal QBank.</p></div><section class="grid two"><div class="card"><h2>Add or edit content</h2><p>Question editing, answers, sources, PYQ details, images, tags, and taxonomy are protected by editor-only Supabase policies.</p><p class="notice">The migration creates the content tables and safety controls. Connect an authenticated editor role before exposing write controls.</p></div><div class="card"><h2>Content quality</h2><p>Question reports are stored with type and details so corrections can be reviewed without deleting historical test snapshots.</p><a href="#/qbank" class="button secondary">Practice questions</a></div></section>`); }
async function openOne(id) { const { data, error } = await db.from('questions').select('*').eq('id', id).single(); if (error) return toast(error.message); state.active = { kind: 'practice', title: 'Review question', questions: [await questionWithOptions(data)], index: 0, answers: {}, marked: {}, explain: 'after', startedAt: new Date().toISOString() }; renderActive(); }

async function render() { clearInterval(state.timer); state.route = route(); if (!state.user) return auth(); try { if (state.route === 'home') return home(); if (state.route === 'qbank') return qbank(); if (state.route === 'tests') return tests(); if (state.route === 'history') return history(); if (state.route === 'bookmarks') return simpleQuestionList('bookmarks'); if (state.route === 'review') return simpleQuestionList('review'); if (state.route === 'analytics') return analytics(); if (state.route === 'manage') return manage(); return home(); } catch (error) { layout(`<div class="card notice"><b>Something went wrong.</b><p>${e(error.message || 'Please try again.')}</p></div>`); } }
function auth() { root.innerHTML = `<main class="shell auth"><section class="card"><h1>QBank Hub</h1><p class="subtle">Your private medical study workspace.</p>${initError ? `<div class="notice">${e(initError)}</div>` : ''}<form id="auth-form" class="stack"><div class="field"><label>Email</label><input class="input" required name="email" type="email" autocomplete="email" /></div><div class="field"><label>Password</label><input class="input" required name="password" type="password" autocomplete="current-password" minlength="6" /></div><button class="button" ${db ? '' : 'disabled'}>Sign in</button><button class="button secondary" type="button" data-action="signup" ${db ? '' : 'disabled'}>Create account</button><button class="button ghost" type="button" data-action="reset" ${db ? '' : 'disabled'}>Reset password</button></form><p class="auth-switch subtle">Your session stays synchronized securely across your devices.</p></section></main>`; document.querySelector('#auth-form').onsubmit = signIn; }
async function signIn(event) { event.preventDefault(); if (!db) return toast(initError); const f = Object.fromEntries(new FormData(event.currentTarget)); const { error } = await db.auth.signInWithPassword(f); if (error) return toast(error.message); }
async function signUp() { if (!db) return toast(initError); const form = document.querySelector('#auth-form'); const f = Object.fromEntries(new FormData(form)); const { data, error } = await db.auth.signUp(f); if (error) return toast(error.message); toast(data.session ? 'Account created.' : 'Account created. Check your email to confirm it.'); }
async function resetPassword() { if (!db) return toast(initError); const email = document.querySelector('[name=email]').value.trim(); if (!email) return toast('Enter your email first.'); const { error } = await db.auth.resetPasswordForEmail(email, { redirectTo: location.origin }); if (error) toast(error.message); else toast('Password reset email sent.'); }

document.addEventListener('click', async (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const action = target.dataset.action; if (action === 'signout') await db.auth.signOut(); if (action === 'signup') await signUp(); if (action === 'reset') await resetPassword(); if (action === 'answer') await selectAnswer(target.dataset.key); if (action === 'previous') { state.active.index--; if (state.active.kind === 'test') await saveTestAnswer(activeQuestion().id, state.active.answers[activeQuestion().id]?.selected_option || null); renderActive(); } if (action === 'next') { if (state.active.index === state.active.questions.length - 1) return state.active.kind === 'test' ? submitTest() : home(); state.active.index++; if (state.active.kind === 'test') await saveTestAnswer(activeQuestion().id, state.active.answers[activeQuestion().id]?.selected_option || null); renderActive(); } if (action === 'jump') { state.active.index = Number(target.dataset.index); if (state.active.kind === 'test') await saveTestAnswer(activeQuestion().id, state.active.answers[activeQuestion().id]?.selected_option || null); renderActive(); } if (action === 'bookmark') await toggleBookmark(); if (action === 'mark') await toggleMark(); if (action === 'note') await noteModal(); if (action === 'report') reportModal(); if (action === 'close-modal') document.querySelector('#modal')?.remove(); if (action === 'submit') await submitTest(); if (action === 'resume') await resumeTest(target.dataset.id); if (action === 'open-one') await openOne(target.dataset.id); if (action === 'review-result') { state.active.index = 0; state.active.kind = 'practice'; state.active.explain = 'after'; renderActive(); } });
window.addEventListener('hashchange', render);
async function bootstrap() {
  loading();
  state.user = await requireUser();
  if (db) {
    try { await loadMeta(); } catch (error) { console.error('QBank startup metadata failed', error); }
    db.auth.onAuthStateChange((_event, session) => { state.user = session?.user || null; render(); });
  }
  render();
}
bootstrap();
