import {remaining,pinManualSelection,rotateEarly,effectivePreferences,readServerPreferences,saveServerPreferences} from './smart-recall-preferences.mjs';
import {SUBJECTS,BUCKETS,LABELS,freshPreferences,readPreferences,validatePreferences,allocate,buildPlan} from './smart-recall-model.mjs';
import {loadRecallPools} from './smart-recall-data.mjs';
export function createSmartRecall({db,state,e,toast,prepareQuestionSet,readyScreen,returnHome,storage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)},loadPools=loadRecallPools}) {
 let preferences=freshPreferences(),plan=null,pools=null,owner=null,generation=0,busy=false,revision=0,notice=[],coverage=[],temporarySubject='';
 const effective=()=>effectivePreferences(preferences,temporarySubject);
 const valid=token=>token===generation&&state.user?.id===owner&&state.route==='home';
 const focusLabel=()=>temporarySubject?`${temporarySubject} today`:({prep:'Current prep mix',all:'All subjects',active:'Active subjects only',early:'Early exposure subjects',custom:'Custom subject selection'}[preferences.focus]);
 const countsHtml=counts=>`<div class="smart-recall-counts">${BUCKETS.map(b=>`<div><span>${LABELS[b]}</span><b>${counts[b]}</b></div>`).join('')}</div>`;
 function card(){if(owner!==state.user?.id)temporarySubject='';owner=state.user?.id;preferences={...readPreferences(storage,owner),size:30};plan=null;pools=null;return `<section class="card section-card smart-recall" id="smart-recall"><div class="section-heading"><div><span class="eyebrow">RECALL TODAY</span><h2>Recall Today — ${preferences.size} questions</h2><p class="subtle">Your mix of important PYQs, mistakes, saved questions and revision.</p></div></div><div id="smart-recall-summary" aria-live="polite">${countsHtml(allocate(preferences.size,preferences.weights))}<p>Target mix · Checking available questions…</p></div><div id="smart-recall-actions" class="smart-recall-actions"><button class="button" data-smart="mixed" disabled>Start Smart Recall</button><button class="button secondary" data-smart="customize">Customize Mix</button><button class="button secondary" data-smart="importance" disabled>Global Importance only</button><button class="button secondary" data-smart="mistakes" disabled>Mistakes only</button></div><label class="field">Temporary subject focus<select id="smart-recall-today"><option value="">Use saved study mix</option>${SUBJECTS.map(s=>`<option value="${e(s)}" ${temporarySubject===s?'selected':''}>${e(s)} today</option>`).join('')}</select><small>Only this subject for this visit. Saved subjects stay unchanged.</small></label><div id="smart-recall-editor"></div></section>`;}
 function showSummary(){const holder=document.querySelector('#smart-recall-summary');if(!holder||!plan)return;document.querySelector('#smart-recall h2').textContent=`Recall Today — ${plan.selected.length} questions`;
 const scope=temporarySubject|| (preferences.focus==='prep'?`${preferences.active.join(', ')} + early exposure: ${preferences.early.join(', ')}`:preferences.focus==='all'?'All 19 subjects':preferences[preferences.focus].join(', '));
 holder.innerHTML=`${notice.length?`<div class="notice" role="status">${notice.map(n=>`<p>${e(n)}</p>`).join('')}<button class="button ghost compact" data-smart="dismiss-notice">Dismiss</button></div>`:''}${countsHtml(plan.counts)}<p><b>Global Importance focus: ${e(focusLabel())}</b><br>${e(scope)}</p>${!temporarySubject&&preferences.focus==='prep'?`<p class="subtle">Global Importance: ${plan.activeImportance} active + ${plan.earlyImportance} early exposure · target ${preferences.activePercent}% / ${100-preferences.activePercent}%</p>`:''}${plan.fallbackCount?`<p class="subtle">${plan.fallbackCount} places filled from available fallback questions. Counts above show the actual mix.</p>`:''}${plan.shortfall?`<p class="notice">${plan.selected.length} eligible questions available for your requested ${plan.requested}. No duplicates added.</p>`:''}<details><summary>Concept coverage</summary>${coverage.filter(c=>temporarySubject?c.subject===temporarySubject:[...preferences.active,...preferences.early].includes(c.subject)).map(c=>`<p>${e(c.subject)} · HIGH ${c.high_covered}/${c.high_total} · MEDIUM ${c.medium_covered}/${c.medium_total}</p>`).join('')}</details><details class="smart-recall-reasons"><summary>Why these questions?</summary><ul>${BUCKETS.filter(b=>plan.counts[b]).map(b=>`<li><b>${LABELS[b]} (${plan.counts[b]})</b>: ${[...new Set(plan.selected.filter(q=>q.bucket===b).map(q=>q.reason))].map(e).join('; ')}</li>`).join('')}</ul></details>`;
 document.querySelectorAll('#smart-recall-actions [data-smart]').forEach(b=>b.disabled=busy||b.dataset.smart!=='customize'&&!plan.selected.length);
 }
 async function mount(){const token=++generation;owner=state.user?.id;busy=true;try{
  const saved=await readServerPreferences(db,owner,preferences);if(!valid(token))return;
  preferences=saved.preferences;revision=saved.revision;notice=saved.notice;
  if(!saved.exists){const initial=await saveServerPreferences(db,preferences,revision,notice);if(!valid(token))return;revision=initial.revision;}
  const counts=await db.rpc('smart_recall_coverage_summary',{p_exam_focus:preferences.examFocus||'All'});if(counts.error)throw counts.error;if(!valid(token))return;coverage=counts.data||[];
  if(!temporarySubject){const rotation=rotateEarly(preferences,coverage);if(rotation.notices.length){
   const changed=await saveServerPreferences(db,rotation.preferences,revision,[...notice,...rotation.notices].slice(-19));if(!valid(token))return;
   preferences=changed.preferences;revision=changed.revision;notice=changed.notice;
  }}
  try{storage.setItem(`qbank-smart-recall-v1:${owner}`,JSON.stringify(preferences));}catch{}
  const next=await loadPools(db,owner,effective(),state.meta.subjects);if(!valid(token))return;pools=next;plan=buildPlan(effective(),pools);busy=false;showSummary();
 }catch(error){if(valid(token)){busy=false;pools=null;const box=document.querySelector('#smart-recall-summary');if(box)box.innerHTML=`<p class="notice">Recall mix could not load: ${e(error.message)}</p><button class="button secondary" data-smart="retry">Retry</button>`;}}}
 const checks=(field,label,draft)=>`<fieldset class="smart-subjects" data-subject-group="${field}"><legend>${label}</legend>${SUBJECTS.map(s=>`<label><input type="checkbox" name="${field}" value="${e(s)}" ${draft[field].includes(s)?'checked':''}> ${e(s==='Obstetrics & Gynecology'?'Obstetrics and Gynaecology':s)}</label>`).join('')}</fieldset>`;
 function customize(draft=preferences){const holder=document.querySelector('#smart-recall-editor');if(!holder)return;
 holder.innerHTML=`<form id="smart-recall-form" class="stack"><h3>Customize Recall Mix</h3><p class="subtle">Subjects and mix are saved to your account across devices. Active subjects never change automatically. Completed Early Exposure subjects can rotate; explicitly reselected completed subjects stay pinned.</p><div class="smart-recall-fields"><p>Daily target: 30 questions</p><label>Global Importance focus<select name="focus">${[['prep','Current prep mix'],['all','All subjects'],['active','Active subjects only'],['early','Early exposure / ignored subjects'],['custom','Custom subject selection']].map(([v,l])=>`<option value="${v}" ${draft.focus===v?'selected':''}>${l}</option>`).join('')}</select></label></div><fieldset><legend>Recall mix percentages (total 100%)</legend><div class="smart-recall-fields">${BUCKETS.map(b=>`<label>${LABELS[b]} %<input name="${b}" type="number" min="0" max="100" step="1" required value="${draft.weights[b]}"></label>`).join('')}</div></fieldset><label data-prep-split>Global Importance from active subjects %<input type="number" name="activePercent" min="0" max="100" step="1" value="${draft.activePercent}" required><small>The rest comes from early exposure subjects.</small></label><div class="smart-subject-groups">${checks('active','Active subjects',draft)}${checks('early','Early exposure subjects',draft)}${checks('custom','Choose Global Importance subjects',draft)}</div><p id="smart-recall-form-error" role="alert"></p><div class="smart-recall-actions"><button class="button" type="submit">Save mix</button><button class="button secondary" type="button" data-smart="preset">Reset to Current prep mix</button><button class="button secondary" type="button" data-smart="close">Cancel</button></div></form>`;
 const form=document.querySelector('#smart-recall-form');const update=()=>{const focus=form.elements.focus.value;form.querySelector('[data-prep-split]').hidden=focus!=='prep';for(const f of ['active','early','custom'])form.querySelector(`[data-subject-group="${f}"]`).hidden=!(focus===f||focus==='prep'&&f!=='custom');};form.elements.focus.onchange=update;update();form.elements.focus.focus();
 form.onsubmit=async event=>{event.preventDefault();if(busy)return;const token=generation;busy=true;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{
  const data=new FormData(form);const next=pinManualSelection({version:1,size:30,focus:data.get('focus'),active:data.getAll('active'),early:data.getAll('early'),custom:data.getAll('custom'),activePercent:Number(data.get('activePercent')),weights:Object.fromEntries(BUCKETS.map(b=>[b,Number(data.get(b))]))},coverage);validatePreferences(next);
  const saved=await saveServerPreferences(db,next,revision,[]);if(!valid(token))return;preferences=saved.preferences;revision=saved.revision;notice=[];holder.innerHTML='';plan=null;pools=null;document.querySelector('#smart-recall-summary').innerHTML='<p role="status">Updating your saved study mix…</p>';await mount();
 }catch(error){if(valid(token))document.querySelector('#smart-recall-form-error').textContent=error.message;}finally{if(valid(token)){busy=false;submit.disabled=false;}}};

 }
 async function start(mode,button){if(busy||!pools)return;const token=generation;busy=true;const label=button.textContent;button.textContent='Preparing Recall…';document.querySelectorAll('#smart-recall-actions button').forEach(b=>b.disabled=true);try{
  const chosen=buildPlan(effective(),pools,mode);if(!chosen.selected.length){toast('No eligible questions in this selection.');return;}
  // Fetch labels only for the chosen set, including personal revision outside the GI frontier.
  const labels=await db.from('pyq_concept_importance').select('subject,concept_id,primary_concept,global_importance_tier,question_ids').overlaps('question_ids',chosen.selected.map(q=>q.question_id));
  if(!valid(token))return;
  if(labels.error)throw labels.error;
  const byQuestion=new Map((labels.data||[]).flatMap(c=>c.question_ids.map(id=>[id,c])));
  chosen.selected=chosen.selected.map(q=>{const c=byQuestion.get(q.question_id);return c?{...q,concept_id:c.concept_id,primary_concept:c.primary_concept,tier:c.global_importance_tier}:q;});
  const details={version:1,exam_focus:preferences.examFocus||'All',size:30,mode,counts:chosen.counts,fallbackCount:chosen.fallbackCount,shortfall:chosen.shortfall,focus:focusLabel(),questions:chosen.selected.map(({question_id,bucket,reason,reasons,subject,primary_concept,concept_id,tier})=>({question_id,bucket,reason,reasons,subject,primary_concept,concept_id,tier}))};
  const set=await prepareQuestionSet({mode:'recall',preset:'smart-recall',title:mode==='importance'?'Global Importance Recall':mode==='mistakes'?'Mistakes Recall':'Recall Today',questionIds:chosen.selected.map(q=>q.question_id),filters:{smart_recall:details},requested:30,autoSubmit:false,origin:'#/home'});
  if(valid(token))readyScreen(set);
 }catch(error){if(valid(token)){toast(error.message||'Could not prepare Recall.','error');const box=document.querySelector('#smart-recall');if(!box)returnHome();}}finally{if(valid(token)){busy=false;if(button.isConnected)button.textContent=label;showSummary();}}}
 document.querySelector('#app').addEventListener('click',event=>{const button=event.target.closest('[data-smart]');if(!button||state.route!=='home'||!state.user||state.user.id!==owner)return;const action=button.dataset.smart;
  if(action==='dismiss-notice'&&!busy){const token=generation;busy=true;void saveServerPreferences(db,preferences,revision,[]).then(saved=>{if(valid(token)){revision=saved.revision;notice=[];showSummary();}}).catch(error=>toast(error.message,'error')).finally(()=>{if(valid(token)){busy=false;showSummary();}});return;}if(action==='customize'&&!busy)return customize();if(action==='close'){document.querySelector('#smart-recall-editor').innerHTML='';return;}if(action==='preset')return customize(freshPreferences());if(action==='retry'&&!busy)return mount();if(['mixed','importance','mistakes'].includes(action))void start(action,button);
 });
 document.querySelector('#app').addEventListener('change',event=>{if(event.target.id!=='smart-recall-today'||state.user?.id!==owner)return;temporarySubject=event.target.value;plan=null;pools=null;document.querySelector('#smart-recall-summary').innerHTML='<p role="status">Updating today’s focus…</p>';void mount();});
 return {card,mount,cancel(){generation++;busy=false;pools=null;plan=null;}};
}
