import {SUBJECTS,BUCKETS,LABELS,freshPreferences,readPreferences,validatePreferences,allocate,buildPlan} from './smart-recall-model.mjs';
import {loadRecallPools} from './smart-recall-data.mjs';
export function createSmartRecall({db,state,e,toast,prepareQuestionSet,readyScreen,returnHome,storage={getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)},loadPools=loadRecallPools}) {
 let preferences=freshPreferences(),plan=null,pools=null,owner=null,generation=0,busy=false;
 const valid=token=>token===generation&&state.user?.id===owner&&state.route==='home';
 const focusLabel=()=>({prep:'Current prep mix',all:'All subjects',active:'Active subjects only',early:'Early exposure subjects',custom:'Custom subject selection'}[preferences.focus]);
 const countsHtml=counts=>`<div class="smart-recall-counts">${BUCKETS.map(b=>`<div><span>${LABELS[b]}</span><b>${counts[b]}</b></div>`).join('')}</div>`;
 function card(){owner=state.user?.id;preferences=readPreferences(storage,owner);plan=null;pools=null;return `<section class="card section-card smart-recall" id="smart-recall"><div class="section-heading"><div><span class="eyebrow">RECALL TODAY</span><h2>Recall Today — ${preferences.size} questions</h2><p class="subtle">Your mix of important PYQs, mistakes, saved questions and revision.</p></div></div><div id="smart-recall-summary" aria-live="polite">${countsHtml(allocate(preferences.size,preferences.weights))}<p>Target mix · Checking available questions…</p></div><div id="smart-recall-actions" class="smart-recall-actions"><button class="button" data-smart="mixed" disabled>Start Smart Recall</button><button class="button secondary" data-smart="customize">Customize Mix</button><button class="button secondary" data-smart="importance" disabled>Global Importance only</button><button class="button secondary" data-smart="mistakes" disabled>Mistakes only</button></div><div id="smart-recall-editor"></div></section>`;}
 function showSummary(){const holder=document.querySelector('#smart-recall-summary');if(!holder||!plan)return;document.querySelector('#smart-recall h2').textContent=`Recall Today — ${plan.selected.length} questions`;
 const scope=preferences.focus==='prep'?`${preferences.active.join(', ')} + early exposure: ${preferences.early.join(', ')}`:preferences.focus==='all'?'All 19 subjects':preferences[preferences.focus].join(', ');
 holder.innerHTML=`${countsHtml(plan.counts)}<p><b>Global Importance focus: ${e(focusLabel())}</b><br>${e(scope)}</p>${preferences.focus==='prep'?`<p class="subtle">Global Importance: ${plan.activeImportance} active + ${plan.earlyImportance} early exposure · target ${preferences.activePercent}% / ${100-preferences.activePercent}%</p>`:''}${plan.fallbackCount?`<p class="subtle">${plan.fallbackCount} places filled from available fallback questions. Counts above show the actual mix.</p>`:''}${plan.shortfall?`<p class="notice">${plan.selected.length} eligible questions available for your requested ${plan.requested}. No duplicates added.</p>`:''}<details class="smart-recall-reasons"><summary>Why these questions?</summary><ul>${BUCKETS.filter(b=>plan.counts[b]).map(b=>`<li><b>${LABELS[b]} (${plan.counts[b]})</b>: ${[...new Set(plan.selected.filter(q=>q.bucket===b).map(q=>q.reason))].map(e).join('; ')}</li>`).join('')}</ul></details>`;
 document.querySelectorAll('#smart-recall-actions [data-smart]').forEach(b=>b.disabled=busy||b.dataset.smart!=='customize'&&!plan.selected.length);
 }
 async function mount(){const token=++generation;owner=state.user?.id;busy=true;try{const next=await loadPools(db,owner,preferences,state.meta.subjects);if(!valid(token))return;pools=next;plan=buildPlan(preferences,pools);busy=false;showSummary();}catch(error){if(valid(token)){busy=false;const box=document.querySelector('#smart-recall-summary');if(box)box.innerHTML=`<p class="notice">Recall mix could not load: ${e(error.message)}</p><button class="button secondary" data-smart="retry">Retry</button>`;}}}
 const checks=(field,label,draft)=>`<fieldset class="smart-subjects" data-subject-group="${field}"><legend>${label}</legend>${SUBJECTS.map(s=>`<label><input type="checkbox" name="${field}" value="${e(s)}" ${draft[field].includes(s)?'checked':''}> ${e(s==='Obstetrics & Gynecology'?'Obstetrics and Gynaecology':s)}</label>`).join('')}</fieldset>`;
 function customize(draft=preferences){const holder=document.querySelector('#smart-recall-editor');if(!holder)return;
 holder.innerHTML=`<form id="smart-recall-form" class="stack"><h3>Customize Recall Mix</h3><p class="subtle">Preferences are saved for your account on this device. Personal mistakes and saved questions can still come from any subject.</p><div class="smart-recall-fields"><label>Questions<select name="size">${[10,20,30,50].map(n=>`<option ${draft.size===n?'selected':''}>${n}</option>`).join('')}</select></label><label>Global Importance focus<select name="focus">${[['prep','Current prep mix'],['all','All subjects'],['active','Active subjects only'],['early','Early exposure / ignored subjects'],['custom','Custom subject selection']].map(([v,l])=>`<option value="${v}" ${draft.focus===v?'selected':''}>${l}</option>`).join('')}</select></label></div><fieldset><legend>Recall mix percentages (total 100%)</legend><div class="smart-recall-fields">${BUCKETS.map(b=>`<label>${LABELS[b]} %<input name="${b}" type="number" min="0" max="100" step="1" required value="${draft.weights[b]}"></label>`).join('')}</div></fieldset><label data-prep-split>Global Importance from active subjects %<input type="number" name="activePercent" min="0" max="100" step="1" value="${draft.activePercent}" required><small>The rest comes from early exposure subjects.</small></label><div class="smart-subject-groups">${checks('active','Active subjects',draft)}${checks('early','Early exposure subjects',draft)}${checks('custom','Choose Global Importance subjects',draft)}</div><p id="smart-recall-form-error" role="alert"></p><div class="smart-recall-actions"><button class="button" type="submit">Save mix</button><button class="button secondary" type="button" data-smart="preset">Reset to Current prep mix</button><button class="button secondary" type="button" data-smart="close">Cancel</button></div></form>`;
 const form=document.querySelector('#smart-recall-form');const update=()=>{const focus=form.elements.focus.value;form.querySelector('[data-prep-split]').hidden=focus!=='prep';for(const f of ['active','early','custom'])form.querySelector(`[data-subject-group="${f}"]`).hidden=!(focus===f||focus==='prep'&&f!=='custom');};form.elements.focus.onchange=update;update();form.elements.size.focus();
 form.onsubmit=event=>{event.preventDefault();try{const data=new FormData(form),next={version:1,size:Number(data.get('size')),focus:data.get('focus'),active:data.getAll('active'),early:data.getAll('early'),custom:data.getAll('custom'),activePercent:Number(data.get('activePercent')),weights:Object.fromEntries(BUCKETS.map(b=>[b,Number(data.get(b))]))};validatePreferences(next);preferences=next;try{storage.setItem(`qbank-smart-recall-v1:${owner}`,JSON.stringify(next));}catch{toast('Mix applied for this visit; device storage is unavailable.');}holder.innerHTML='';plan=null;pools=null;document.querySelector('#smart-recall-summary').innerHTML=`${countsHtml(allocate(next.size,next.weights))}<p role="status">Updating available questions…</p>`;document.querySelectorAll('#smart-recall-actions button:not([data-smart="customize"])').forEach(b=>b.disabled=true);void mount();}catch(error){document.querySelector('#smart-recall-form-error').textContent=error.message;}};
 }
 async function start(mode,button){if(busy||!pools)return;const token=generation;busy=true;const label=button.textContent;button.textContent='Preparing Recall…';document.querySelectorAll('#smart-recall-actions button').forEach(b=>b.disabled=true);try{
  const chosen=buildPlan(preferences,pools,mode);if(!chosen.selected.length){toast('No eligible questions in this selection.');return;}
  // Fetch labels only for the chosen set, including personal revision outside the GI frontier.
  const labels=await db.from('pyq_concept_importance').select('subject,concept_id,primary_concept,global_importance_tier,question_ids').overlaps('question_ids',chosen.selected.map(q=>q.question_id));
  if(!valid(token))return;
  if(labels.error)throw labels.error;
  const byQuestion=new Map((labels.data||[]).flatMap(c=>c.question_ids.map(id=>[id,c])));
  chosen.selected=chosen.selected.map(q=>{const c=byQuestion.get(q.question_id);return c?{...q,concept_id:c.concept_id,primary_concept:c.primary_concept,tier:c.global_importance_tier}:q;});
  const details={version:1,exam_focus:preferences.examFocus||'All',size:preferences.size,mode,counts:chosen.counts,fallbackCount:chosen.fallbackCount,shortfall:chosen.shortfall,focus:focusLabel(),questions:chosen.selected.map(({question_id,bucket,reason,subject,primary_concept,concept_id,tier})=>({question_id,bucket,reason,subject,primary_concept,concept_id,tier}))};
  const set=await prepareQuestionSet({mode:'recall',preset:'smart-recall',title:mode==='importance'?'Global Importance Recall':mode==='mistakes'?'Mistakes Recall':'Recall Today',questionIds:chosen.selected.map(q=>q.question_id),filters:{smart_recall:details},requested:preferences.size,autoSubmit:false,origin:'#/home'});
  if(valid(token))readyScreen(set);
 }catch(error){if(valid(token)){toast(error.message||'Could not prepare Recall.','error');const box=document.querySelector('#smart-recall');if(!box)returnHome();}}finally{if(valid(token)){busy=false;if(button.isConnected)button.textContent=label;showSummary();}}}
 document.querySelector('#app').addEventListener('click',event=>{const button=event.target.closest('[data-smart]');if(!button||state.route!=='home'||!state.user||state.user.id!==owner)return;const action=button.dataset.smart;
  if(action==='customize')return customize();if(action==='close'){document.querySelector('#smart-recall-editor').innerHTML='';return;}if(action==='preset')return customize(freshPreferences());if(action==='retry'&&!busy)return mount();if(['mixed','importance','mistakes'].includes(action))void start(action,button);
 });
 return {card,mount,cancel(){generation++;busy=false;pools=null;plan=null;}};
}
