import { db, initError, requireUser } from './supabase.js';

const VERSION='canonical-medical-v1';
const ids=['version-line','auth-message','error-message','summary','taxonomy-tree','sample-size','metrics','review-progress','page-status','review-filters','sample-search','sample-subject','sample-status','sample-confidence','sample-review','page-size','clear-filters','review-loading','sample-rows','previous-page','next-page','page-line','previous-question','next-question','next-unreviewed','next-low','next-ambiguous','question-review','detail-title','close-detail','detail-loading','detail-content','source-context','question-stem','question-options','correct-answer','question-explanation','question-media','proposal-path','proposal-fields','proposal-flags','proposal-rationale','full-question-id','copy-question-id','correction-fields','correct-subject','correct-system','correct-topic','correct-subtopic','corrected-path','secondary-concept','secondary-results','reviewer-note','save-review','save-status'];
const el=Object.fromEntries(ids.map((id)=>[id,document.getElementById(id)]));
const state={overview:null,page:1,pageSize:25,total:0,items:[],active:null,decision:null,secondaryId:null,childCache:new Map(),contentCache:new Map(),request:0,detailRequest:0};
const pct=(value,total=1)=>total?`${Math.round(Number(value)*1000/Number(total))/10}%`:'0%';
function showError(message){el['error-message'].textContent=message;el['error-message'].hidden=false;}
function metric(value,label){const card=document.createElement('div');card.className='metric';const strong=document.createElement('strong');strong.textContent=value;const span=document.createElement('span');span.textContent=label;card.append(strong,span);return card;}
function option(value,label){const node=document.createElement('option');node.value=value;node.textContent=label;return node;}
function classifierStatus(row){if(Number(row.classifier_confidence)===0)return'unclassifiable';if(row.ambiguity||row.cross_subject_ambiguity)return'ambiguous';return'classified';}
function confidenceBand(value){value=Number(value);return value===0?'none':value<.5?'low':value<.8?'medium':'high';}
function reviewLabel(value){return({accepted:'Accepted',needs_correction:'Needs correction',unclassifiable:'Unclassifiable',defer:'Deferred'})[value]||'Unreviewed';}
function friendlyId(value){return `Q-${String(value||'').replaceAll('-','').slice(0,8).toUpperCase()}`;}
function basisLabel(value){return({source_topic_supported:'Source-topic supported',content_override:'Content override',content_only:'Content-led',ambiguous:'Ambiguous',unclassifiable:'Unclassifiable'})[value]||'Draft evidence';}
function sanitizeHtml(value){const template=document.createElement('template');template.innerHTML=String(value||'');template.content.querySelectorAll('script,style,iframe,object,embed,form,link,meta').forEach((node)=>node.remove());template.content.querySelectorAll('*').forEach((node)=>[...node.attributes].forEach((attribute)=>{const name=attribute.name.toLowerCase();if(name.startsWith('on')||['srcdoc','style'].includes(name))node.removeAttribute(attribute.name);if(['href','src'].includes(name)&&/^\s*javascript:/i.test(attribute.value))node.removeAttribute(attribute.name);}));return template.content;}

async function children(parentId){if(state.childCache.has(parentId))return state.childCache.get(parentId);const {data,error}=await db.rpc('qbank_taxonomy_review_children',{p_version_key:VERSION,p_parent_id:parentId});if(error)throw error;state.childCache.set(parentId,data||[]);return data||[];}
function nodeLabel(node){const wrap=document.createElement('span');wrap.className='tree-label';for(const [className,text] of [['node-type',node.type||node.node_type],['node-name',node.name],['node-path',node.path]]){const span=document.createElement('span');span.className=className;span.textContent=text;wrap.append(span);}return wrap;}
function buildTreeNode(node){if((node.type||node.node_type)==='subtopic'){const leaf=document.createElement('div');leaf.className='leaf';leaf.append(nodeLabel(node));return leaf;}const details=document.createElement('details');details.dataset.nodeId=node.id;const summary=document.createElement('summary');summary.append(nodeLabel(node));const holder=document.createElement('div');holder.className='tree-children';details.append(summary,holder);details.addEventListener('toggle',async()=>{if(!details.open||details.dataset.loaded)return;details.dataset.loaded='true';holder.textContent='Loading branch…';try{const rows=await children(node.id);holder.replaceChildren(...rows.map(buildTreeNode));if(!rows.length){holder.textContent='No child nodes.';holder.classList.add('muted');}}catch(error){delete details.dataset.loaded;holder.textContent=error.message;}});return details;}
function renderTree(){el['taxonomy-tree'].replaceChildren(...(state.overview.subjects||[]).map(buildTreeNode));}

function filters(){return{p_version_key:VERSION,p_page:state.page,p_page_size:state.pageSize,p_subject:el['sample-subject'].value||null,p_status:el['sample-status'].value||null,p_confidence:el['sample-confidence'].value||null,p_review_state:el['sample-review'].value||null,p_search:el['sample-search'].value.trim()||null};}
async function loadPage({openFirst=false}={}){const request=++state.request;el['review-loading'].hidden=false;const started=performance.now();const {data,error}=await db.rpc('qbank_taxonomy_review_page',filters());if(request!==state.request)return;if(error)throw error;state.total=Number(data.total||0);state.items=data.items||[];state.page=Number(data.page||1);state.pageSize=Number(data.page_size||25);renderRows();renderProgress(data,performance.now()-started);el['review-loading'].hidden=true;if(openFirst&&state.items[0])await openQuestion(state.items[0]);}
function renderProgress(data,elapsed){el['review-progress'].textContent=`Reviewed ${Number(data.reviewed||0).toLocaleString()} / ${Number(data.sample_total||0).toLocaleString()}`;el['page-status'].textContent=`${state.total.toLocaleString()} match · ${Math.round(elapsed)} ms`;const pages=Math.max(1,Math.ceil(state.total/state.pageSize));el['page-line'].textContent=`Page ${state.page} of ${pages}`;el['previous-page'].disabled=state.page<=1;el['next-page'].disabled=state.page>=pages;}
function badge(text,className=''){const span=document.createElement('span');span.className=`flag ${className}`.trim();span.textContent=text;return span;}
function appendBasisBadges(target,row){target.append(badge(basisLabel(row.classification_basis),row.source_topic_supported?'source':''));if(row.classification_level==='topic')target.append(badge('Topic-level only'));if(row.classification_level==='subtopic')target.append(badge('Subtopic identified','high'));if(row.classification_level==='concept')target.append(badge('Canonical concept identified','high'));if(row.content_override)target.append(badge('Content overrides source','cross'));if(row.ambiguity)target.append(badge('Ambiguous'));if(row.cross_subject_ambiguity)target.append(badge('Cross-subject','cross'));}
function renderRows(){const body=el['sample-rows'];body.replaceChildren();for(const row of state.items){const tr=document.createElement('tr');tr.dataset.questionId=row.question_id;if(state.active?.question_id===row.question_id)tr.classList.add('active-row');const open=document.createElement('td');const button=document.createElement('button');button.type='button';button.className='open-question';button.textContent='Open';button.addEventListener('click',()=>openQuestion(row));open.append(button);const qid=document.createElement('td');qid.className='question-id';qid.textContent=friendlyId(row.question_id);const source=document.createElement('td');source.textContent=`${row.platform}${row.source_test?` · ${row.source_test}`:''}${row.is_pyq?' · PYQ':''}`;const subject=document.createElement('td');subject.textContent=row.existing_subject;const path=document.createElement('td');path.className='path';path.textContent=row.proposed_path||'No draft match';const confidence=document.createElement('td');confidence.textContent=`${pct(row.classifier_confidence)} · ${confidenceBand(row.classifier_confidence)}`;const basis=document.createElement('td');appendBasisBadges(basis,row);const review=document.createElement('td');review.append(badge(reviewLabel(row.review_decision),row.review_decision==='accepted'?'high':''));if(row.corrected_path){const corrected=document.createElement('div');corrected.className='corrected-summary';corrected.textContent=row.corrected_path;review.append(corrected);}tr.append(open,qid,source,subject,path,confidence,basis,review);body.append(tr);}if(!state.items.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=8;td.className='muted';td.textContent='No review questions match these filters.';tr.append(td);body.append(tr);}}

function renderRich(target,html,empty='Not available'){target.replaceChildren();if(!html){target.textContent=empty;target.classList.add('muted');return;}target.classList.remove('muted');target.append(sanitizeHtml(html));}
function addDefinition(list,label,value){const dt=document.createElement('dt');dt.textContent=label;const dd=document.createElement('dd');dd.textContent=value||'—';list.append(dt,dd);}
function renderQuestionContent(data){
  const source=data.source||{};el['source-context'].replaceChildren();
  addDefinition(el['source-context'],'Platform',source.platform);
  addDefinition(el['source-context'],'Existing Subject',source.subject);
  addDefinition(el['source-context'],'Source Test / Module',source.source_test);
  addDefinition(el['source-context'],'Context',[source.position?`Question ${source.position}`:'',source.is_pyq?'PYQ':'',source.exam_year||''].filter(Boolean).join(' · ')||'—');
  addDefinition(el['source-context'],'Source-supported Topic',state.active?.source_evidence_topic||'No reliable topic clue from source title');
  renderRich(el['question-stem'],data.content?.stem,'Question stem unavailable');el['question-options'].replaceChildren();
  for(const item of data.content?.options||[]){const li=document.createElement('li');const key=document.createElement('strong');key.textContent=`${item.key}. `;li.append(key,sanitizeHtml(item.html));if((data.content.correct_keys||[]).includes(item.key))li.classList.add('correct-option');el['question-options'].append(li);}
  el['correct-answer'].textContent=(data.content?.correct_keys||[]).join(', ')||'Not available';renderRich(el['question-explanation'],data.content?.explanation,'No explanation available');el['question-media'].replaceChildren();
  const refs=[...(data.content?.media||[]),...(data.content?.audio?[{placement:'audio',reference:data.content.audio}]:[]),...(data.content?.video?[{placement:'video',reference:data.content.video}]:[]),...(data.media_reference?[{placement:'question',reference:data.media_reference}]:[])];
  if(refs.length){const title=document.createElement('strong');title.textContent='Media references';el['question-media'].append(title);for(const media of refs){const line=document.createElement('div');line.textContent=`${media.placement}: ${typeof media.reference==='string'?media.reference:JSON.stringify(media.reference)}`;el['question-media'].append(line);}}else el['question-media'].textContent='No media references.';
}
function renderProposal(row){el['proposal-path'].textContent=row.proposed_concept_path||row.proposed_path||'Unclassifiable in this draft';el['proposal-fields'].replaceChildren();const used=row.evidence_usage||{};const evidence=[used.subject_prior?'Subject prior':'',used.source_topic?'Source title':'',used.stem?'Stem':'',used.correct_answer?'Correct answer':'',used.explanation_positive?'Explanation positive points':''].filter(Boolean).join(' · ');for(const pair of [['Canonical Subject',row.existing_subject],['System',row.proposed_system],['Topic',row.proposed_topic],['Subtopic',row.proposed_subtopic],['Canonical Concept',row.proposed_concept],['Confidence',pct(row.classifier_confidence)],['Concept confidence',row.proposed_concept?pct(row.concept_confidence):null],['Positive evidence used',evidence],['Secondary / related concept',row.secondary_concept]])addDefinition(el['proposal-fields'],...pair);el['proposal-flags'].replaceChildren();appendBasisBadges(el['proposal-flags'],row);el['proposal-rationale'].textContent=row.reason;el['full-question-id'].textContent=row.question_id;}
async function openQuestion(row){const detailRequest=++state.detailRequest;state.active=row;state.decision=row.review_decision||null;state.secondaryId=row.secondary_node_id||null;renderRows();el['question-review'].hidden=false;el['detail-content'].hidden=true;el['detail-loading'].hidden=false;el['detail-loading'].textContent='Loading only this question’s content…';el['detail-title'].textContent=`Review ${friendlyId(row.question_id)}`;el['question-stem'].replaceChildren();el['question-options'].replaceChildren();el['question-explanation'].replaceChildren();el['save-status'].textContent='';renderProposal(row);await initializeReview(row);if(detailRequest!==state.detailRequest)return;try{let content=state.contentCache.get(row.question_id);if(!content){const result=await db.functions.invoke('taxonomy-review-question',{body:{question_id:row.question_id}});if(result.error)throw result.error;content=result.data;state.contentCache.set(row.question_id,content);}if(detailRequest!==state.detailRequest||state.active?.question_id!==row.question_id)return;renderQuestionContent(content);el['detail-loading'].hidden=true;el['detail-content'].hidden=false;el['question-review'].scrollIntoView({behavior:'smooth',block:'start'});}catch(error){if(detailRequest===state.detailRequest)el['detail-loading'].textContent=`Question content could not be loaded: ${error.message}`;}}

function setSelect(select,rows,placeholder,selected=''){select.replaceChildren(option('',placeholder),...rows.map((row)=>option(row.id,row.name)));select.value=selected||'';}
function updateCorrectedPath(){const parts=[el['correct-subject'],el['correct-system'],el['correct-topic'],el['correct-subtopic']].map((select)=>select.selectedOptions[0]?.value?select.selectedOptions[0].textContent:'').filter(Boolean);el['corrected-path'].textContent=parts.length?parts.join(' → '):'Choose a subject and topic';}
async function loadCorrectionSubject(saved={}){const subjectId=el['correct-subject'].value;setSelect(el['correct-system'],[],'No system / select');setSelect(el['correct-topic'],[],'Select topic');setSelect(el['correct-subtopic'],[],'No subtopic / select');if(!subjectId){updateCorrectedPath();return;}const rows=await children(subjectId);const systems=rows.filter((row)=>row.node_type==='system');const directTopics=rows.filter((row)=>row.node_type==='topic');setSelect(el['correct-system'],systems,'No system / direct topic',saved.system||'');if(saved.system)await loadCorrectionSystem(saved.topic||'');else setSelect(el['correct-topic'],directTopics,'Select topic',saved.topic||'');if(saved.topic)await loadCorrectionTopic(saved.subtopic||'');updateCorrectedPath();}
async function loadCorrectionSystem(selectedTopic=''){const systemId=el['correct-system'].value;if(!systemId){const direct=(await children(el['correct-subject'].value)).filter((row)=>row.node_type==='topic');setSelect(el['correct-topic'],direct,'Select topic',selectedTopic);setSelect(el['correct-subtopic'],[],'No subtopic / select');updateCorrectedPath();return;}const rows=await children(systemId);setSelect(el['correct-topic'],rows.filter((row)=>row.node_type==='topic'),'Select topic',selectedTopic);setSelect(el['correct-subtopic'],[],'No subtopic / select');updateCorrectedPath();}
async function loadCorrectionTopic(selectedSubtopic=''){const topicId=el['correct-topic'].value;if(!topicId){setSelect(el['correct-subtopic'],[],'No subtopic / select');updateCorrectedPath();return;}const rows=await children(topicId);setSelect(el['correct-subtopic'],rows.filter((row)=>row.node_type==='subtopic'),'No subtopic / select',selectedSubtopic);updateCorrectedPath();}
function setDecision(decision){state.decision=decision;el['correction-fields'].hidden=decision!=='needs_correction';document.querySelectorAll('[data-decision]').forEach((button)=>button.classList.toggle('selected',button.dataset.decision===decision));el['save-status'].textContent=decision?'Decision selected. Save to persist this draft review.':'Choose a review decision.';}
async function initializeReview(row){el['correct-subject'].replaceChildren(option('','Select subject'),...(state.overview.subjects||[]).map((subject)=>option(subject.id,subject.name)));el['reviewer-note'].value=row.reviewer_note||'';el['secondary-concept'].value=row.secondary_path||'';el['secondary-results'].hidden=true;setDecision(row.review_decision||null);if(row.review_decision==='needs_correction'){el['correct-subject'].value=row.corrected_subject_id||'';await loadCorrectionSubject({system:row.corrected_system_id,topic:row.corrected_topic_id,subtopic:row.corrected_subtopic_id});}}
async function saveReview(){if(!state.active||!state.decision){el['save-status'].textContent='Choose a review decision first.';return;}if(state.decision==='accepted'&&!state.active.proposed_node_id){el['save-status'].textContent='This proposal has no canonical node to accept.';return;}if(state.decision==='needs_correction'&&!el['correct-topic'].value){el['save-status'].textContent='Select a corrected Topic before saving.';return;}el['save-review'].disabled=true;el['save-status'].textContent='Saving draft review…';const correction=state.decision==='needs_correction';const {error}=await db.rpc('qbank_save_taxonomy_draft_review',{p_version_key:VERSION,p_question_id:state.active.question_id,p_decision:state.decision,p_proposed_node_id:state.active.proposed_node_id||null,p_corrected_subject_id:correction?el['correct-subject'].value:null,p_corrected_system_id:correction?(el['correct-system'].value||null):null,p_corrected_topic_id:correction?el['correct-topic'].value:null,p_corrected_subtopic_id:correction?(el['correct-subtopic'].value||null):null,p_secondary_node_id:state.secondaryId||null,p_reviewer_note:el['reviewer-note'].value||null,p_proposal_snapshot:{path:state.active.proposed_path,confidence:state.active.classifier_confidence,reason:state.active.reason}});el['save-review'].disabled=false;if(error){el['save-status'].textContent=`Could not save: ${error.message}`;return;}el['save-status'].textContent='Draft review saved. It is not a production assignment.';const activeId=state.active.question_id;await loadPage();const refreshed=state.items.find((row)=>row.question_id===activeId);if(refreshed){state.active=refreshed;renderRows();}}

async function jump(kind){state.page=1;if(kind==='unreviewed')el['sample-review'].value='unreviewed';if(kind==='low')el['sample-confidence'].value='low';if(kind==='ambiguous')el['sample-status'].value='ambiguous';await loadPage({openFirst:true});}
function moveQuestion(offset){if(!state.active)return;const index=state.items.findIndex((row)=>row.question_id===state.active.question_id);const target=state.items[index+offset];if(target)openQuestion(target);}
let searchTimer,secondaryTimer;
function schedulePage(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.page=1;loadPage().catch((error)=>showError(error.message));},300);}
function scheduleSecondary(){clearTimeout(secondaryTimer);secondaryTimer=setTimeout(async()=>{const query=el['secondary-concept'].value.trim();state.secondaryId=null;if(query.length<2){el['secondary-results'].hidden=true;return;}const {data,error}=await db.rpc('qbank_taxonomy_review_node_search',{p_version_key:VERSION,p_search:query,p_limit:25});if(error)return;el['secondary-results'].replaceChildren(option('','Choose a matching concept'),...(data||[]).map((row)=>option(row.id,row.path)));el['secondary-results'].hidden=false;},250);}

async function init(){if(initError||!db){showError(initError||'Supabase client is unavailable.');return;}const user=await requireUser();if(!user){el['auth-message'].hidden=false;el['auth-message'].textContent='Sign in to QBank Hub first, then return to this internal review page.';return;}const started=performance.now();const {data,error}=await db.rpc('qbank_taxonomy_review_overview',{p_version_key:VERSION});if(error)throw error;state.overview=data;el['version-line'].replaceChildren();const name=document.createElement('span');name.textContent=data.version.name;const status=document.createElement('span');status.className='status';status.textContent=data.version.status;el['version-line'].append(name,status);el.summary.replaceChildren(...[['subject','Subjects'],['system','Systems'],['topic','Topics'],['subtopic','Subtopics']].map(([key,label])=>metric(data.counts[key]||0,label)));renderTree();for(const subject of data.subjects||[])el['sample-subject'].append(option(subject.name,subject.name));el['sample-size'].textContent=`${Number(data.sample_total||0).toLocaleString()} questions`;const total=Number(data.sample_total||0),metrics=data.metrics||{};el.metrics.replaceChildren(metric(pct(metrics.high,total),'High confidence'),metric(pct(metrics.ambiguous,total),'Ambiguous'),metric(pct(metrics.unclassifiable,total),'Unclassifiable'),metric(pct(metrics.cross_subject,total),'Cross-subject ambiguity'));await loadPage();el['page-status'].dataset.initialLoadMs=String(Math.round(performance.now()-started));}

el['review-filters'].addEventListener('change',()=>{state.page=1;state.pageSize=Number(el['page-size'].value);loadPage().catch((error)=>showError(error.message));});el['sample-search'].addEventListener('input',schedulePage);
el['clear-filters'].addEventListener('click',()=>{el['review-filters'].reset();state.page=1;state.pageSize=25;loadPage().catch((error)=>showError(error.message));});
el['previous-page'].addEventListener('click',()=>{state.page--;loadPage().catch((error)=>showError(error.message));});el['next-page'].addEventListener('click',()=>{state.page++;loadPage().catch((error)=>showError(error.message));});
el['previous-question'].addEventListener('click',()=>moveQuestion(-1));el['next-question'].addEventListener('click',()=>moveQuestion(1));el['next-unreviewed'].addEventListener('click',()=>jump('unreviewed'));el['next-low'].addEventListener('click',()=>jump('low'));el['next-ambiguous'].addEventListener('click',()=>jump('ambiguous'));
el['close-detail'].addEventListener('click',()=>{state.detailRequest++;el['question-review'].hidden=true;state.active=null;renderRows();});document.querySelectorAll('[data-decision]').forEach((button)=>button.addEventListener('click',()=>setDecision(button.dataset.decision)));
el['correct-subject'].addEventListener('change',()=>loadCorrectionSubject().catch((error)=>showError(error.message)));el['correct-system'].addEventListener('change',()=>loadCorrectionSystem().catch((error)=>showError(error.message)));el['correct-topic'].addEventListener('change',()=>loadCorrectionTopic().catch((error)=>showError(error.message)));el['correct-subtopic'].addEventListener('change',updateCorrectedPath);
el['secondary-concept'].addEventListener('input',scheduleSecondary);el['secondary-results'].addEventListener('change',()=>{state.secondaryId=el['secondary-results'].value||null;if(state.secondaryId)el['secondary-concept'].value=el['secondary-results'].selectedOptions[0].textContent;});el['save-review'].addEventListener('click',saveReview);
el['copy-question-id'].addEventListener('click',async()=>{if(!state.active)return;const button=el['copy-question-id'];try{await navigator.clipboard.writeText(state.active.question_id);button.textContent='Copied';}catch{button.textContent='Copy unavailable';}setTimeout(()=>{button.textContent='Copy UUID';},1200);});
init().catch((error)=>showError(error.message||String(error)));
