begin;
insert into auth.users(id) values('00000000-0000-4000-8000-000000008801');
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000008801',true);
create temp table checks(name text,passed boolean);
create temp table fixture as select q.id from public.questions q where q.is_usable and q.correct_answer='A' and not exists(select 1 from public.active_recall_reliable_map m where m.question_id=q.id) limit 1;
grant select on fixture to authenticated;
grant select,insert on checks to authenticated;
set local role authenticated;
select public.qbank_active_recall_manual(id,'add',gen_random_uuid()) from fixture;
select public.qbank_active_recall_manual(id,'add',gen_random_uuid()) from fixture;
insert into checks select 'manual add is idempotent',count(*)=1 from public.active_recall_units where user_id=auth.uid();
insert into checks select 'unmapped fallback',unit_key='q:'||(select id from fixture) from public.qbank_active_recall_rows();
select public.qbank_active_recall_record(id,'B',gen_random_uuid(),null,20,'failed',null) from fixture;
select public.qbank_active_recall_record(id,'B',gen_random_uuid(),null,20,'strong','forgot') from fixture;
insert into checks select 'wrong despite strong is WEAK',mastery='WEAK' and interval_minutes=15 and consecutive_failures=2 from public.active_recall_units where user_id=auth.uid();
insert into checks select 'universal attempts and mistakes retained',count(*)=2 and count(*) filter(where is_correct)=0 and count(*) filter(where error_reason='forgot')=1 from public.question_attempts where user_id=auth.uid();
select public.qbank_active_recall_record(id,'A',gen_random_uuid(),null,20,'partial',null) from fixture;
insert into checks select 'partial cannot advance',interval_minutes=15 and spaced_successes=0 from public.active_recall_units where user_id=auth.uid();
-- Simulate real elapsed days on the synthetic account only.
do $$declare n integer; q uuid;begin
 select id into q from fixture;
 for n in 1..6 loop
 update public.active_recall_units set last_reviewed_at=now()-interval '3 days' where user_id=auth.uid();
 update public.user_question_state set srm_last_reviewed_at=now()-interval '3 days' where user_id=auth.uid();
 perform public.qbank_active_recall_record(q,'A',gen_random_uuid(),null,20,'strong',null);
 end loop;
end$$;
insert into checks select 'spaced strong reaches maintenance',mastery='MASTERED' and interval_minutes=86400 and active from public.active_recall_units where user_id=auth.uid();
select public.qbank_active_recall_record(id,'B',gen_random_uuid(),null,20,'failed',null) from fixture;
insert into checks select 'later failure downgrades',mastery='LEARNING' and interval_minutes=15 from public.active_recall_units where user_id=auth.uid();
create temp table event_fixture as select gen_random_uuid() id;
select public.qbank_active_recall_record(f.id,'A',e.id,null,20,'strong',null) from fixture f cross join event_fixture e;
select public.qbank_active_recall_record(f.id,'A',e.id,null,20,'strong',null) from fixture f cross join event_fixture e;
insert into checks select 'retry records one attempt',count(*)=1 from public.question_attempts where user_id=auth.uid() and client_event_id=(select id from event_fixture);
insert into checks select 'immediate success graduates without mastery credit',interval_minutes=1440 and spaced_successes=0 and mastery='LEARNING' from public.active_recall_units where user_id=auth.uid() and unit_key like 'q:%';
update public.active_recall_retrievals set error_reason='misread' where user_id=auth.uid() and event_id=(select id from event_fixture);
insert into checks select 'optional mistake annotation retained',error_reason='misread' from public.active_recall_retrievals where user_id=auth.uid() and event_id=(select id from event_fixture);
insert into checks select 'bookmark and review independent',not bookmarked and not marked_for_review and not revision from public.user_question_state where user_id=auth.uid();
create temp table mapped_fixture as select subject,concept_id,question_ids from public.pyq_concept_importance where cardinality(question_ids)>1 and not exists(select 1 from unnest(question_ids) q where not exists(select 1 from public.active_recall_reliable_map m where m.question_id=q)) limit 1;
select public.qbank_active_recall_manual(q,'add',gen_random_uuid()) from mapped_fixture cross join lateral unnest(question_ids) q;
insert into checks select 'reliable questions aggregate',count(*)=1 from public.qbank_active_recall_rows() where unit->>'primary_concept' is not null;
select public.qbank_active_recall_record(q.id,q.correct_answer,gen_random_uuid(),null,20,'strong',null) from public.questions q where q.id=(select question_ids[1] from mapped_fixture);
insert into checks select 'reliable variant rotates',(unit->>'question_id')::uuid<>(select question_ids[1] from mapped_fixture) from public.qbank_active_recall_rows() where unit->>'primary_concept' is not null;
insert into checks select 'legacy individual schedules survive',count(*)=(select cardinality(question_ids) from mapped_fixture)+1 from public.user_question_state where user_id=auth.uid();
insert into checks select 'draft canonical mappings excluded',not exists(select 1 from public.active_recall_reliable_map where mapping_count<>1);
select public.qbank_active_recall_manual(question_ids[1],'remove',gen_random_uuid()) from mapped_fixture;
insert into checks select 'concept removal excludes unit',not (unit->>'active')::boolean from public.qbank_active_recall_rows() where unit->>'primary_concept' is not null;
select public.qbank_active_recall_manual(question_ids[1],'add',gen_random_uuid()) from mapped_fixture;
-- A confident ordinary attempt must not revive stale due dates of another member.
update public.active_recall_units set due_at=now()+interval '7 days',updated_at=now()-interval '1 hour' where user_id=auth.uid() and unit_key like 'c:%';
update public.user_question_state set srm_last_reviewed_at=now()-interval '2 hours',srm_due_at=now()-interval '1 day',last_is_correct=true,last_confidence='sure' where user_id=auth.uid() and question_id in(select unnest(question_ids) from mapped_fixture);
update public.user_question_state set srm_last_reviewed_at=now(),srm_due_at=now()+interval '3 days' where user_id=auth.uid() and question_id=(select question_ids[1] from mapped_fixture);
insert into checks select 'ordinary confidence does not resurrect stale concept members',(unit->>'due_at')::timestamptz>now() from public.qbank_active_recall_rows() where unit->>'primary_concept' is not null;
update public.user_question_state set last_is_correct=false,srm_consecutive_incorrect=2,srm_due_at=now()-interval '1 minute' where user_id=auth.uid() and question_id=(select question_ids[1] from mapped_fixture);
insert into checks select 'later ordinary lapse reenters weak recall',unit->>'mastery'='WEAK' and (unit->>'due_at')::timestamptz<=now() from public.qbank_active_recall_rows() where unit->>'primary_concept' is not null;
insert into checks select 'readd preserves individual history',count(*)>=10 from public.qbank_srm_events where user_id=auth.uid();
select set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000008802',true);
grant select,insert on checks to authenticated;
set local role authenticated;
insert into checks select 'cross-account units hidden',count(*)=0 from public.active_recall_units;
insert into checks select 'cross-account retrievals hidden',count(*)=0 from public.active_recall_retrievals;
insert into checks select 'cross-account queue empty',(public.qbank_active_recall_queue()->>'due_count')::integer=0;
reset role;
select jsonb_agg(to_jsonb(checks)) results from checks;
rollback;
