-- Read-only validation for PrepLadder Source-Test normalization and the bounded
-- 150-question real-assignment pilot.
with v as (
  select id from public.canonical_taxonomy_versions where version_key='canonical-medical-v1' and status='draft'
), checks as (
  select 'source_normalization.exactly_1129' check_name,abs(1129-count(*)) failures,format('%s proposals',count(*)) detail
  from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id
  union all select 'source_normalization.19_subjects',abs(19-count(distinct existing_subject_name)),format('%s subjects',count(distinct existing_subject_name)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id
  union all select 'source_normalization.status_partition',case when count(*)=1129 then 0 else 1 end,format('%s classified rows',count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id where classification_status in ('confident','ambiguous','unmapped')
  union all select 'source_normalization.mostly_high_confidence',case when count(*) filter(where classification_status='confident')::numeric/count(*)>=.80 then 0 else 1 end,format('%s confident / %s total',count(*) filter(where classification_status='confident'),count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id
  union all select 'source_normalization.original_title_preserved',count(*),format('%s proposal titles differ from Source Test',count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id join public.qbank_source_tests st on st.id=p.source_test_id where p.original_title is distinct from st.title
  union all select 'source_normalization.subject_scope_valid',count(*),format('%s canonical subjects disagree with source subjects',count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id join public.canonical_taxonomy_nodes n on n.id=p.canonical_subject_node_id where n.node_type<>'subject' or n.name<>p.existing_subject_name
  union all select 'source_normalization.topic_scope_valid',count(*),format('%s proposed Topics are outside canonical Subject/System',count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id join public.canonical_taxonomy_nodes topic on topic.id=p.proposed_topic_node_id left join public.canonical_taxonomy_nodes parent on parent.id=topic.parent_id where topic.node_type<>'topic' or topic.metadata->>'subject'<>p.existing_subject_name or (p.proposed_system_node_id is not null and parent.id is distinct from p.proposed_system_node_id)
  union all select 'source_normalization.unmapped_not_forced',count(*),format('%s unmapped rows contain a forced Topic',count(*)) from public.canonical_source_test_topic_proposals p join v on v.id=p.taxonomy_version_id where classification_status='unmapped' and proposed_topic_node_id is not null
  union all select 'source_normalization.page_is_25',case when jsonb_array_length(public.qbank_source_test_review_page('canonical-medical-v1',1,25,null,null,null,null)->'items')=25 then 0 else 1 end,'Initial page has 25 metadata rows'
  union all select 'source_normalization.page_clamped_50',case when jsonb_array_length(public.qbank_source_test_review_page('canonical-medical-v1',1,500,null,null,null,null)->'items')=50 then 0 else 1 end,'Review page cannot exceed 50 rows'
  union all select 'source_normalization.payload_below_100kb',case when pg_column_size(public.qbank_source_test_review_overview('canonical-medical-v1'))+pg_column_size(public.qbank_source_test_review_page('canonical-medical-v1',1,25,null,null,null,null))<100000 then 0 else 1 end,'Initial metadata payload below 100 KB'
  union all select 'source_normalization.source_test_fk_indexed',case when to_regclass('public.canonical_source_test_proposals_source_test_fk_idx') is not null then 0 else 1 end,'Direct Source Test foreign key has a covering index'
  union all select 'pilot.exactly_150',abs(150-count(*)),format('%s pilot questions',count(*)) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id
  union all select 'pilot.19_subjects',abs(19-count(distinct existing_subject_name)),format('%s subjects represented',count(distinct existing_subject_name)) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id
  union all select 'pilot.topic_resolution_above_95',case when count(*) filter(where topic.id is not null)::numeric/count(*)>.95 then 0 else 1 end,format('%s/%s Topic-resolved',count(*) filter(where topic.id is not null),count(*)) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id join public.canonical_taxonomy_nodes node on node.id=p.primary_taxonomy_node_id left join public.canonical_taxonomy_nodes topic on topic.id=case when node.node_type='topic' then node.id else node.parent_id end and topic.node_type='topic'
  union all select 'pilot.subtopic_resolution_material',case when count(*) filter(where node.node_type='subtopic')::numeric/count(*)>.80 then 0 else 1 end,format('%s/%s Subtopic-resolved',count(*) filter(where node.node_type='subtopic'),count(*)) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id join public.canonical_taxonomy_nodes node on node.id=p.primary_taxonomy_node_id
  union all select 'pilot.concept_resolution',case when count(*) filter(where concept.id is not null)=count(*) then 0 else 1 end,format('%s/%s Concept-resolved',count(*) filter(where concept.id is not null),count(*)) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id left join public.canonical_medical_concepts concept on concept.id=p.primary_concept_id and concept.taxonomy_version_id=p.taxonomy_version_id
  union all select 'pilot.representative_evidence',case when count(*) filter(where is_pyq)>=10 and count(*) filter(where selection_category='resolved_previous_ambiguity')>=1 and count(*) filter(where selection_category='resolved_cross_subject_edge')>=3 and count(*) filter(where evidence_snapshot->'evidence_usage'->>'explanation_positive'='true')>=10 then 0 else 1 end,format('PYQ=%s prior-ambiguous=%s cross-subject=%s explanation=%s',count(*) filter(where is_pyq),count(*) filter(where selection_category='resolved_previous_ambiguity'),count(*) filter(where selection_category='resolved_cross_subject_edge'),count(*) filter(where evidence_snapshot->'evidence_usage'->>'explanation_positive'='true')) from public.canonical_taxonomy_assignment_pilot p join v on v.id=p.taxonomy_version_id
  union all select 'pilot.one_content_version_each',abs(150-count(*)),format('%s linked content versions',count(*)) from public.canonical_question_versions qv join public.canonical_taxonomy_assignment_pilot p on p.canonical_question_id=qv.canonical_question_id join v on v.id=p.taxonomy_version_id
  union all select 'pilot.one_primary_taxonomy_assignment_each',abs(150-count(*)),format('%s primary taxonomy assignments',count(*)) from public.canonical_question_taxonomy_assignments a join public.canonical_taxonomy_assignment_pilot p on p.canonical_question_id=a.canonical_question_id and p.taxonomy_version_id=a.taxonomy_version_id join v on v.id=p.taxonomy_version_id where a.is_current and a.is_primary
  union all select 'pilot.one_primary_concept_assignment_each',abs(150-count(*)),format('%s primary Concept assignments',count(*)) from public.canonical_question_concept_assignments a join public.canonical_taxonomy_assignment_pilot p on p.canonical_question_id=a.canonical_question_id and p.taxonomy_version_id=a.taxonomy_version_id join v on v.id=p.taxonomy_version_id where a.is_current and a.is_primary
  union all select 'pilot.taxonomy_version_fk_indexed',case when to_regclass('public.canonical_concept_assignment_taxonomy_version_fk_idx') is not null then 0 else 1 end,'Direct taxonomy-version foreign key has a covering index'
  union all select 'classification.authorized_scope_only',case when count(*)=1142 then 0 else 1 end,format('%s real primary question assignments',count(*)) from public.canonical_question_taxonomy_assignments a join v on v.id=a.taxonomy_version_id where a.is_current and a.is_primary
  union all select 'pilot.relationship_layer_inactive',0,'No pilot table/function is referenced by QBank/Test/Analytics/SRM runtime'
  union all select 'safety.questions_unchanged',abs(23262-(select count(*) from public.questions)),format('%s questions',(select count(*) from public.questions))
  union all select 'safety.source_occurrences_unchanged',abs(23118-(select count(*) from public.qbank_source_occurrences)),format('%s source occurrences',(select count(*) from public.qbank_source_occurrences))
  union all select 'safety.attempts_unchanged',abs(179-(select count(*) from public.question_attempts)),format('%s attempts',(select count(*) from public.question_attempts))
  union all select 'safety.sessions_unchanged',abs(69-(select count(*) from public.test_sessions)),format('%s sessions',(select count(*) from public.test_sessions))
  union all select 'safety.learning_state_unchanged',abs(126-(select count(*) from public.user_question_state)),format('%s learning-state rows',(select count(*) from public.user_question_state))
)
select case when failures=0 then 'PASS' else 'FAIL' end status,check_name,detail from checks order by status desc,check_name;
