-- Concise, read-only validation for Canonical Taxonomy v1 DRAFT.
with v as (
  select id,status from public.canonical_taxonomy_versions where version_key='canonical-medical-v1'
), checks as (
  select 'taxonomy.version_is_draft' check_name,
    case when (select count(*) from v where status='draft')=1 then 0 else 1 end failures,
    'Exactly one Canonical Taxonomy v1 draft version' details
  union all select 'taxonomy.19_subjects',abs(19-(select count(*) from public.canonical_taxonomy_nodes n join v on v.id=n.taxonomy_version_id where n.node_type='subject')),'All 19 MBBS/NEET-PG subjects'
  union all select 'taxonomy.no_orphans',count(*),format('%s orphan nodes',count(*)) from public.canonical_taxonomy_nodes n join v on v.id=n.taxonomy_version_id left join public.canonical_taxonomy_nodes p on p.id=n.parent_id where n.node_type<>'subject' and p.id is null
  union all select 'taxonomy.valid_optional_system_hierarchy',count(*),format('%s invalid parent relationships',count(*)) from public.canonical_taxonomy_nodes n join v on v.id=n.taxonomy_version_id left join public.canonical_taxonomy_nodes p on p.id=n.parent_id where (n.node_type='subject' and n.parent_id is not null) or (n.node_type='system' and p.node_type<>'subject') or (n.node_type='topic' and p.node_type not in ('subject','system')) or (n.node_type='subtopic' and p.node_type<>'topic')
  union all select 'taxonomy.no_duplicate_codes',count(*),format('%s duplicate stable codes',count(*)) from (select stable_code from public.canonical_taxonomy_nodes n join v on v.id=n.taxonomy_version_id group by stable_code having count(*)>1) d
  union all select 'taxonomy.assignments_are_authorized_bounded',case when count(*) filter(where a.is_current and a.is_primary)=1145 and count(*)=2170 then 0 else 1 end,format('%s current primary assignments; %s total path assignments',count(*) filter(where a.is_current and a.is_primary),count(*)) from public.canonical_question_taxonomy_assignments a join v on v.id=a.taxonomy_version_id
  union all select 'taxonomy.no_assignments_outside_authorized_runs',count(*),format('%s assignments exist outside the pilot and authorized 1000 batch generations',count(*)) from public.canonical_question_taxonomy_assignments a join v on v.id=a.taxonomy_version_id left join public.canonical_taxonomy_assignment_pilot p on p.canonical_question_id=a.canonical_question_id and p.taxonomy_version_id=a.taxonomy_version_id where p.question_id is null and not exists (select 1 from public.canonical_classification_runs r where r.id=a.classification_run_id and r.scope_key in ('canonical-medical-v1-prepladder-batch-1000-01','canonical-medical-v1-prepladder-batch-1000-quality-v2'))
  union all select 'taxonomy.canonical_links_are_authorized_bounded',case when (select count(*) from public.canonical_questions)=1150 and (select count(*) from public.canonical_question_versions)=1150 then 0 else 1 end,format('%s canonical identities; %s version links',(select count(*) from public.canonical_questions),(select count(*) from public.canonical_question_versions))
  union all select 'taxonomy.dry_run_is_bounded',case when count(*) between 300 and 500 then 0 else 1 end,format('%s deterministic sample rows',count(*)) from public.qbank_taxonomy_classification_dry_run('canonical-medical-v1',380)
  union all select 'taxonomy.dry_run_subject_coverage',abs(19-count(distinct existing_subject)),format('%s/19 subjects sampled',count(distinct existing_subject)) from public.qbank_taxonomy_classification_dry_run('canonical-medical-v1',380)
  union all select 'taxonomy.dry_run_no_invalid_paths',count(*),format('%s classified rows lack a canonical path',count(*)) from public.qbank_taxonomy_classification_dry_run('canonical-medical-v1',380) where classifier_confidence>0 and proposed_path is null
  union all select 'taxonomy.review_sample_is_bounded',case when count(*) between 300 and 500 then 0 else 1 end,format('%s materialized draft rows',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id
  union all select 'taxonomy.review_sample_subject_coverage',abs(19-count(distinct existing_subject)),format('%s/19 subjects in draft review sample',count(distinct existing_subject)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id
  union all select 'taxonomy.review_page_is_25',case when jsonb_array_length(public.qbank_taxonomy_review_page('canonical-medical-v1',1,25,null,null,null,null,null)->'items')=25 then 0 else 1 end,'Initial review page contains 25 metadata rows'
  union all select 'taxonomy.review_page_clamps_to_50',case when jsonb_array_length(public.qbank_taxonomy_review_page('canonical-medical-v1',1,500,null,null,null,null,null)->'items')=50 then 0 else 1 end,'Review page cannot exceed 50 rows'
  union all select 'taxonomy.review_metadata_payload_bounded',case when pg_column_size(public.qbank_taxonomy_review_overview('canonical-medical-v1'))+pg_column_size(public.qbank_taxonomy_review_page('canonical-medical-v1',1,25,null,null,null,null,null))<100000 then 0 else 1 end,'Initial database JSON payload remains below 100 KB'
  union all select 'taxonomy.source_evidence_strategy_present',case when count(*) filter(where classification_basis='source_topic_supported')>0 and count(*) filter(where classification_basis='content_override')>0 and count(*) filter(where classification_basis='ambiguous')>0 and count(*) filter(where classification_level='topic')>0 and count(*) filter(where classification_level='subtopic')>0 and count(*) filter(where classification_level='unclassifiable')>0 then 0 else 1 end,format('source=%s override=%s ambiguous=%s topic=%s subtopic=%s unclassifiable=%s',count(*) filter(where classification_basis='source_topic_supported'),count(*) filter(where classification_basis='content_override'),count(*) filter(where classification_basis='ambiguous'),count(*) filter(where classification_level='topic'),count(*) filter(where classification_level='subtopic'),count(*) filter(where classification_level='unclassifiable')) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id
  union all select 'taxonomy.topic_level_has_no_forced_subtopic',count(*),format('%s topic-level rows have a subtopic',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id where classification_level='topic' and proposed_subtopic is not null
  union all select 'taxonomy.v3_evidence_is_same_bounded_sample',abs((select count(*) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id)-(select count(*) from public.canonical_taxonomy_draft_evidence e join v on v.id=e.taxonomy_version_id)),format('%s evidence rows',(select count(*) from public.canonical_taxonomy_draft_evidence e join v on v.id=e.taxonomy_version_id))
  union all select 'taxonomy.v3_vocabulary_covers_every_subject',abs(19-count(distinct subject_name)),format('%s subjects; %s concepts',count(distinct subject_name),count(*)) from public.canonical_medical_concepts c join v on v.id=c.taxonomy_version_id
  union all select 'taxonomy.v3_unclassifiable_is_rare_not_zero',case when count(*) between 5 and 40 then 0 else 1 end,format('%s/380 remain genuinely unresolved',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id where classifier_confidence=0
  union all select 'taxonomy.v3_resolves_prior_failures',case when count(*)>=20 then 0 else 1 end,format('%s previously unclassifiable rows now resolved',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id join public.canonical_taxonomy_draft_evidence e on e.taxonomy_version_id=s.taxonomy_version_id and e.question_id=s.question_id where coalesce((e.evidence_metadata->>'before_confidence')::numeric,0)=0 and s.classifier_confidence>0
  union all select 'taxonomy.v3_source_topic_evidence',case when count(*)>=10 then 0 else 1 end,format('%s rows use source-topic support',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id where source_topic_supported
  union all select 'taxonomy.v3_explanation_positive_evidence',case when count(*)>=10 then 0 else 1 end,format('%s rows use positive explanation evidence',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id where coalesce((evidence_usage->>'explanation_positive')::boolean,false)
  union all select 'taxonomy.v3_content_overrides',case when count(*)>=5 then 0 else 1 end,format('%s legitimate content overrides',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id where content_override
  union all select 'taxonomy.v3_sickle_crisis_regression',case when count(*)=1 then 0 else 1 end,'Sickle-cell crisis resolves to Hemoglobinopathies and Vaso-occlusive crisis' from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id join public.questions q on q.id=s.question_id where q.question_text ilike '%known case of sickle cell anaemia%' and s.proposed_subtopic='Hemoglobinopathies' and s.proposed_concept='Vaso-occlusive crisis'
  union all select 'taxonomy.v3_no_invalid_concept_links',count(*),format('%s concept links cross version/node boundaries',count(*)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id left join public.canonical_medical_concepts c on c.id=s.proposed_concept_id and c.taxonomy_version_id=s.taxonomy_version_id where s.proposed_concept_id is not null and c.id is null
  union all select 'taxonomy.relationship_seed_is_bounded',case when count(*) between 1 and 25 then 0 else 1 end,format('%s controlled draft/reviewed relations',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id
  union all select 'taxonomy.relationships_link_valid_concepts',count(*),format('%s invalid or cross-version concept endpoints',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id left join public.canonical_medical_concepts source on source.id=r.from_concept_id and source.taxonomy_version_id=r.taxonomy_version_id left join public.canonical_medical_concepts target on target.id=r.to_concept_id and target.taxonomy_version_id=r.taxonomy_version_id where source.id is null or target.id is null
  union all select 'taxonomy.relationships_have_no_self_edges',count(*),format('%s self relations',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id where r.from_concept_id=r.to_concept_id
  union all select 'taxonomy.relationships_have_provenance',count(*),format('%s relations lack provenance/review evidence',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id where nullif(trim(r.source_reference),'') is null or r.confidence is null or r.review_status is null
  union all select 'taxonomy.relationships_have_no_symmetric_duplicates',count(*),format('%s reversed symmetric duplicates',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id join public.canonical_concept_relationships reverse on reverse.taxonomy_version_id=r.taxonomy_version_id and reverse.relationship_type=r.relationship_type and reverse.from_concept_id=r.to_concept_id and reverse.to_concept_id=r.from_concept_id where r.relationship_type in ('same_as','sibling_of','confusable_with','associated_with','good_discriminator','related_but_not_equivalent') and r.id<reverse.id
  union all select 'taxonomy.relationship_hierarchy_matches_parent_links',count(*),format('%s parent_of edges disagree with concept hierarchy',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id join public.canonical_medical_concepts child on child.id=r.to_concept_id and child.taxonomy_version_id=r.taxonomy_version_id where r.relationship_type='parent_of' and child.parent_concept_id is distinct from r.from_concept_id
  union all select 'taxonomy.relationships_not_published',count(*),format('%s relationship edges prematurely published',count(*)) from public.canonical_concept_relationships r join v on v.id=r.taxonomy_version_id where r.review_status='published'
  union all select 'taxonomy.relationship_inverse_projection',case when count(*) filter(where relationship_type='parent_of')=4 and count(*) filter(where relationship_type='child_of')=4 then 0 else 1 end,format('%s parent and %s child projections',count(*) filter(where relationship_type='parent_of'),count(*) filter(where relationship_type='child_of')) from public.canonical_concept_relationships_expanded r join v on v.id=r.taxonomy_version_id
  union all select 'taxonomy.friendly_id_search_round_trips',case when jsonb_array_length(public.qbank_taxonomy_review_page('canonical-medical-v1',1,25,null,null,null,null,(select 'Q-'||upper(substr(replace(s.question_id::text,'-',''),1,8)) from public.canonical_taxonomy_draft_sample s join v on v.id=s.taxonomy_version_id order by s.sample_order limit 1))->'items')=1 then 0 else 1 end,'Friendly Q-XXXXXXXX search resolves exactly one draft question'
  union all select 'taxonomy.review_does_not_expand_authorized_runs',count(*),format('%s assignments exist outside authorized runs',count(*)) from public.canonical_question_taxonomy_assignments a join v on v.id=a.taxonomy_version_id left join public.canonical_taxonomy_assignment_pilot p on p.canonical_question_id=a.canonical_question_id and p.taxonomy_version_id=a.taxonomy_version_id where p.question_id is null and not exists (select 1 from public.canonical_classification_runs r where r.id=a.classification_run_id and r.scope_key in ('canonical-medical-v1-prepladder-batch-1000-01','canonical-medical-v1-prepladder-batch-1000-quality-v2'))
  union all select 'taxonomy.global_evidence_empty',count(*),format('%s evidence rows exist before scoring phase',count(*)) from public.canonical_global_evidence
  union all select 'taxonomy.source_counts_preserved',abs(23262-(select count(*) from public.questions)),format('%s questions', (select count(*) from public.questions))
  union all select 'taxonomy.source_occurrences_preserved',abs(23118-(select count(*) from public.qbank_source_occurrences)),format('%s source occurrences',(select count(*) from public.qbank_source_occurrences))
)
select case when failures=0 then 'PASS' else 'FAIL' end status,check_name,details from checks order by status desc,check_name;
